import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'zh-CN' | 'en' | 'fr' | 'ja';
type Dictionary = Record<string, string>;
const en: Dictionary = {
  'app.ready': 'OAT ready', 'app.setup': 'OAT setup', 'app.settings': 'Settings', 'app.theme': 'Theme', 'app.language': 'Language', 'theme.system': 'System', 'theme.light': 'Light', 'theme.dark': 'Dark',
  'header.collapseResources': 'Collapse resources', 'header.showResources': 'Show resources', 'header.refresh': 'Refresh workspace', 'header.collapseDetails': 'Collapse agent details', 'header.showDetails': 'Show agent details',
  'settings.title': 'Settings', 'settings.general': 'Application preferences', 'settings.globalConfig': 'Global configuration', 'settings.models': 'Global model configuration', 'settings.save': 'Save configuration', 'settings.saved': 'Saved', 'settings.failed': 'Save failed',
  'workspace.back': 'Workspace', 'workspace.operate': 'Operate', 'workspace.insights': 'Insights', 'workspace.configure': 'Configure', 'workspace.tasks': 'Task queue', 'workspace.monitor': 'Live activity', 'workspace.docker': 'Docker runtime', 'workspace.usage': 'Usage', 'workspace.achievements': 'Achievements', 'workspace.config': 'Team config', 'workspace.resources': 'Agent resources', 'workspace.plugins': 'Plugins', 'workspace.channels': 'Channels', 'workspace.settings': 'Settings',
  'taskPanel.title': 'Task panel', 'taskPanel.live': 'LIVE · refreshes every 3 seconds', 'taskPanel.empty': 'No tasks have been created for this project.', 'taskPanel.emptyColumn': 'No tasks in this status.', 'taskPanel.progress': 'Progress',
  'resource.title': 'AGENTIC RESOURCES', 'resource.agent': 'Agent Resources Manager', 'resource.history': 'Conversation history', 'resource.projects': 'PROJECTS', 'resource.thinking': 'Thinking…', 'resource.noProjects': 'No projects are registered.', 'resource.historyTitle': 'Agent Resources Manager history', 'resource.historyText': 'Record organization, team, Agent and workspace management requests.', 'resource.placeholder': 'Ask the Agent Resources Manager about projects or Agent resources…', 'resource.steward': 'Local organization steward', 'resource.scope': 'Scope', 'resource.scopeAccess': 'Projects, team configuration, Agent resources and workspace permissions.', 'resource.taskPolicy': 'Does not receive project work; project Admins own task intake.',
  'chat.you': 'You', 'chat.team': 'Open Agent Team', 'chat.startAdmin': 'Start with the Admin', 'chat.report': 'Agent report feed', 'chat.messageAdmin': 'Message project Admin…', 'chat.addContext': 'Add context', 'chat.approval': 'Request approval', 'chat.voice': 'Voice input', 'chat.admin': 'Local Admin', 'chat.configureModel': 'Configure agent model', 'chat.send': 'Send', 'chat.stop': 'Stop request', 'chat.execution': 'Agent execution', 'chat.live': 'LIVE', 'chat.processing': 'Processing', 'chat.processed': 'Processed', 'chat.seconds': 's', 'chat.thinking': 'Latest reasoning and events',
  'queue.queued': 'Queued', 'queue.drag': 'Drag to reorder', 'queue.delete': 'Delete queued task',
  'status.available': 'Available', 'status.busy': 'Busy', 'status.offline': 'Offline', 'status.attention': 'Needs attention', 'status.queued': 'Queued', 'status.running': 'Running', 'status.review_pending': 'Awaiting review', 'status.completed': 'Completed', 'status.cancelled': 'Cancelled', 'status.failed': 'Failed',
  'agent.none': 'No agent selected', 'agent.choose': 'Choose a project and an Agent from Agentic resources.', 'agent.inbox': 'Task inbox', 'agent.reportOnly': 'Report-only', 'agent.taskProgress': 'Task progress', 'agent.workQueue': 'Work queue', 'agent.noTask': 'No active task assigned.', 'agent.noQueue': 'No queued work.', 'agent.executing': 'Executing now', 'agent.queued': 'Queued for execution', 'agent.awaiting': 'Awaiting new work', 'agent.allowed': 'Allowed information', 'agent.policy': 'Interaction policy', 'agent.project': 'Project', 'agent.model': 'Model', 'agent.workspace': 'Workspace', 'agent.repositories': 'Repositories', 'agent.skills': 'Skills', 'agent.access': 'Access', 'agent.defaultModel': 'Project default', 'agent.projectWorkspace': 'Project workspace', 'agent.noSkills': 'No explicit skills', 'agent.adminAccess': 'Accepts new task requests for this project.', 'agent.readOnlyAccess': 'Read-only reports and execution status. New tasks must go through Admin.', 'agent.tasks': 'tasks', 'agent.delegated': 'Delegated Agents', 'agent.delegatedHint': 'Tasks sent by this Agent',
  'git.title': 'Git delivery', 'git.refresh': 'Refresh Git status', 'git.startProject': 'Start the project to inspect Agent branches and edit Git settings.', 'git.remoteEnabled': 'publishing enabled', 'git.remoteDisabled': 'publishing disabled', 'git.localOnly': 'Local Git only', 'git.identityValid': 'Valid local identity', 'git.identityMissing': 'Local identity incomplete', 'git.merged': 'merged', 'git.pushed': 'pushed', 'git.dirty': 'uncommitted', 'git.clean': 'clean', 'git.notMerged': 'not merged', 'git.configure': 'Local and remote settings', 'git.remoteName': 'Remote name (optional)', 'git.remoteUrl': 'Remote URL (optional)', 'git.userName': 'Git user name', 'git.userEmail': 'Git user email', 'git.enablePush': 'Enable remote publishing', 'git.adminOnly': 'Only Admin can explicitly push a merged release. Credentials stay in SSH Agent or the Git credential helper.', 'git.save': 'Save Git settings', 'git.saving': 'Saving…',
  'docker.title': 'Docker runtime', 'docker.subtitle': 'Inspect and safely manage OAT Agent containers.', 'docker.refresh': 'Refresh', 'docker.engine': 'Docker Engine', 'docker.available': 'Available', 'docker.unavailable': 'Unavailable', 'docker.runtime': 'Project runtime', 'docker.isolated': 'Docker isolation', 'docker.localProcess': 'Local process isolation', 'docker.locked': 'Docker isolation is permanently required', 'docker.canMigrate': 'One-way migration to Docker is available', 'docker.containers': 'Managed containers', 'docker.running': 'running', 'docker.configuration': 'Docker configuration', 'docker.migrate': 'Migrate runtime to Docker', 'docker.noDowngrade': 'Image, network, and limits can change, but Docker cannot be changed back to local processes.', 'docker.migrateHint': 'Migration restarts the project and is irreversible.', 'docker.image': 'Image', 'docker.network': 'Network', 'docker.extraArgs': 'Resource and hardening flags', 'docker.safeArgs': 'Allowed: CPU/memory/PID/ulimit/tmpfs limits, read-only, cap-drop=ALL, and no-new-privileges.', 'docker.saving': 'Saving…', 'docker.saveRestart': 'Save and restart project', 'docker.migrateRestart': 'Migrate and restart project', 'docker.managedContainers': 'Agent containers', 'docker.status': 'Status', 'docker.logs': 'Logs', 'docker.restartAgent': 'Restart idle Agent', 'docker.restarting': 'Restarting…', 'docker.noContainers': 'No managed Agent containers are currently running.', 'docker.migrateToManage': 'Migrate this project to Docker to manage Agent containers.', 'docker.close': 'Close', 'docker.noLogs': 'No log output.', 'docker.migrationConfirm': 'Migrate this project to Docker isolation? This restarts the project and cannot be reversed.',
  'docker.remove': 'Remove orphan', 'docker.removeConfirm': 'Remove this stopped or orphaned OAT container?',
  'error.startProject': 'This view is available after the project starts.', 'loading': 'Loading local control-plane data…',
  'startup.title': 'Initializing Open Agent Team', 'startup.subtitle': 'Preparing your local workspace.', 'startup.services': 'Initializing Desktop services…', 'startup.node': 'Node.js environment', 'startup.oat': 'OAT tool', 'startup.docker': 'Docker environment', 'startup.desktopServices': 'Desktop services', 'startup.pending': 'Waiting to check', 'startup.checking': 'Checking…', 'startup.checkingNode': 'Checking Node.js compatibility…', 'startup.checkingOat': 'Checking the OAT command-line tool…', 'startup.checkingDocker': 'Checking the local Docker environment…', 'startup.ready': 'Ready', 'startup.installing': 'Installing local runtime…', 'startup.installingNode': 'Installing a managed Node.js runtime…', 'startup.installingOat': 'Installing the OAT tool…', 'startup.nodeUnavailable': 'A compatible Node.js runtime is unavailable.', 'startup.oatUnavailable': 'The OAT tool is unavailable.', 'startup.dockerNotInstalled': 'Not installed · configure later in Docker management', 'startup.dockerStopped': 'Installed · Docker Engine is not running', 'startup.dockerPermission': 'Installed · daemon access requires attention', 'startup.dockerDeferred': 'Check unavailable · configure later in Docker management', 'startup.retry': 'Try again', 'startup.failed': 'Startup check failed',
};
const zh: Dictionary = { ...en,
  'app.ready': 'OAT 已就绪', 'app.setup': '配置 OAT', 'app.settings': '设置', 'app.theme': '主题', 'app.language': '语言', 'theme.system': '跟随系统', 'theme.light': '浅色', 'theme.dark': '深色',
  'header.collapseResources': '收起资源', 'header.showResources': '显示资源', 'header.refresh': '刷新工作区', 'header.collapseDetails': '收起 Agent 详情', 'header.showDetails': '显示 Agent 详情',
  'settings.title': '设置', 'settings.general': '应用偏好', 'settings.globalConfig': '全局配置', 'settings.models': '全局模型配置', 'settings.save': '保存配置', 'settings.saved': '已保存', 'settings.failed': '保存失败',
  'workspace.back': '工作区', 'workspace.operate': '运行', 'workspace.insights': '洞察', 'workspace.configure': '配置', 'workspace.tasks': '任务队列', 'workspace.monitor': '实时活动', 'workspace.docker': 'Docker 运行环境', 'workspace.usage': '用量', 'workspace.achievements': '成果', 'workspace.config': '团队配置', 'workspace.resources': 'Agent 资源', 'workspace.plugins': '插件', 'workspace.channels': '通道', 'workspace.settings': '设置',
  'taskPanel.title': '任务面板', 'taskPanel.live': '实时 · 每 3 秒刷新', 'taskPanel.empty': '该项目组暂未创建任务。', 'taskPanel.emptyColumn': '该状态暂无任务。', 'taskPanel.progress': '进度',
  'resource.title': '智能资源', 'resource.agent': '智能体资源主管', 'resource.history': '会话记录', 'resource.projects': '项目', 'resource.thinking': '思考中…', 'resource.noProjects': '尚未注册项目。', 'resource.historyTitle': '智能体资源主管会话记录', 'resource.historyText': '用于记录组织、团队、Agent 与工作区管理请求。', 'resource.placeholder': '向智能体资源主管询问项目或 Agent 资源…', 'resource.steward': '本地组织管理员', 'resource.scope': '范围', 'resource.scopeAccess': '项目、团队配置、Agent 资源与工作区权限。', 'resource.taskPolicy': '不接收项目工作；项目 Admin 负责接收任务。',
  'chat.you': '你', 'chat.startAdmin': '与管理员开始会话', 'chat.report': 'Agent 汇报', 'chat.messageAdmin': '向项目管理员发送消息…', 'chat.addContext': '添加上下文', 'chat.approval': '请求批准', 'chat.voice': '语音输入', 'chat.admin': '本地管理员', 'chat.configureModel': '配置 Agent 模型', 'chat.send': '发送', 'chat.stop': '停止请求', 'chat.execution': 'Agent 执行过程', 'chat.live': '实时', 'chat.processing': '正在处理', 'chat.processed': '已处理', 'chat.seconds': '秒', 'chat.thinking': '最新思考过程与处理事件', 'queue.queued': '排队中', 'queue.drag': '拖拽排序', 'queue.delete': '删除排队任务',
  'status.available': '可用', 'status.busy': '忙碌', 'status.offline': '离线', 'status.attention': '需要处理', 'status.queued': '排队中', 'status.running': '执行中', 'status.review_pending': '等待组长评审', 'status.completed': '已完成', 'status.cancelled': '已取消', 'status.failed': '失败',
  'agent.none': '未选择 Agent', 'agent.choose': '请从智能资源中选择项目和 Agent。', 'agent.inbox': '任务入口', 'agent.reportOnly': '仅汇报', 'agent.taskProgress': '任务进度', 'agent.workQueue': '工作队列', 'agent.noTask': '暂无活跃任务。', 'agent.noQueue': '暂无排队工作。', 'agent.executing': '正在执行', 'agent.queued': '等待执行', 'agent.awaiting': '等待新任务', 'agent.allowed': '允许的信息', 'agent.policy': '交互策略', 'agent.project': '项目', 'agent.model': '模型', 'agent.workspace': '工作区', 'agent.repositories': '仓库', 'agent.skills': '技能', 'agent.access': '访问', 'agent.defaultModel': '项目默认模型', 'agent.projectWorkspace': '项目工作区', 'agent.noSkills': '没有显式技能', 'agent.adminAccess': '接收此项目的新任务请求。', 'agent.readOnlyAccess': '只读汇报和执行状态；新任务必须交给 Admin。', 'agent.tasks': '项任务', 'agent.delegated': '下发任务的 Agent', 'agent.delegatedHint': '由当前 Agent 下发', 'error.startProject': '启动项目后即可使用此视图。', 'loading': '正在加载本地控制面数据…',
  'git.title': 'Git 交付状态', 'git.refresh': '刷新 Git 状态', 'git.startProject': '启动项目后可查看各 Agent 分支并修改 Git 设置。', 'git.remoteEnabled': '已启用远程发布', 'git.remoteDisabled': '未启用远程发布', 'git.localOnly': '仅使用本地 Git', 'git.identityValid': '本地身份有效', 'git.identityMissing': '本地身份不完整', 'git.merged': '已合并', 'git.pushed': '已推送', 'git.dirty': '有未提交修改', 'git.clean': '工作区干净', 'git.notMerged': '未合并', 'git.configure': '本地与远程设置', 'git.remoteName': '远程名称（可选）', 'git.remoteUrl': '远程地址（可选）', 'git.userName': 'Git 用户名', 'git.userEmail': 'Git 用户邮箱', 'git.enablePush': '启用远程发布', 'git.adminOnly': '仅 Admin 可显式推送已合并的 release；凭据由 SSH Agent 或 Git credential helper 管理。', 'git.save': '保存 Git 设置', 'git.saving': '保存中…',
  'docker.title': 'Docker 运行环境', 'docker.subtitle': '查看并安全管理 OAT Agent 容器。', 'docker.refresh': '刷新', 'docker.engine': 'Docker Engine', 'docker.available': '可用', 'docker.unavailable': '不可用', 'docker.runtime': '项目运行模式', 'docker.isolated': 'Docker 隔离', 'docker.localProcess': '本地进程隔离', 'docker.locked': '已永久锁定为 Docker 隔离', 'docker.canMigrate': '可以单向迁移到 Docker', 'docker.containers': '受管容器', 'docker.running': '运行中', 'docker.configuration': 'Docker 配置', 'docker.migrate': '将运行环境迁移到 Docker', 'docker.noDowngrade': '可以修改镜像、网络和资源限制，但不能降级回本地进程。', 'docker.migrateHint': '迁移会重启项目，而且不可逆。', 'docker.image': '镜像', 'docker.network': '网络', 'docker.extraArgs': '资源与安全参数', 'docker.safeArgs': '允许 CPU、内存、PID、ulimit、tmpfs 限制，以及只读、cap-drop=ALL 和 no-new-privileges。', 'docker.saving': '保存中…', 'docker.saveRestart': '保存并重启项目', 'docker.migrateRestart': '迁移并重启项目', 'docker.managedContainers': 'Agent 容器', 'docker.status': '状态', 'docker.logs': '日志', 'docker.restartAgent': '重启空闲 Agent', 'docker.restarting': '重启中…', 'docker.noContainers': '当前没有正在运行的受管 Agent 容器。', 'docker.migrateToManage': '将项目迁移到 Docker 后即可管理 Agent 容器。', 'docker.close': '关闭', 'docker.noLogs': '没有日志输出。', 'docker.migrationConfirm': '确定将项目迁移到 Docker 隔离吗？项目会重启，而且迁移不可逆。',
  'docker.remove': '清理孤儿容器', 'docker.removeConfirm': '确定清理这个已停止或孤立的 OAT 容器吗？',
  'startup.title': '正在初始化 Open Agent Team', 'startup.subtitle': '正在准备本地工作区。', 'startup.services': '正在初始化 Desktop 服务…', 'startup.node': 'Node.js 环境', 'startup.oat': 'OAT 工具', 'startup.docker': 'Docker 环境', 'startup.desktopServices': 'Desktop 服务', 'startup.pending': '等待检查', 'startup.checking': '检查中…', 'startup.checkingNode': '正在检查 Node.js 兼容性…', 'startup.checkingOat': '正在检查 OAT 命令行工具…', 'startup.checkingDocker': '正在检查本地 Docker 环境…', 'startup.ready': '已就绪', 'startup.installing': '正在安装本地运行环境…', 'startup.installingNode': '正在安装受管 Node.js 运行环境…', 'startup.installingOat': '正在安装 OAT 工具…', 'startup.nodeUnavailable': '没有可用的兼容 Node.js 运行环境。', 'startup.oatUnavailable': 'OAT 工具不可用。', 'startup.dockerNotInstalled': '未安装 · 可稍后在 Docker 管理中配置', 'startup.dockerStopped': '已安装 · Docker Engine 未运行', 'startup.dockerPermission': '已安装 · daemon 访问权限需要处理', 'startup.dockerDeferred': '暂时无法检查 · 可稍后在 Docker 管理中配置', 'startup.retry': '重试', 'startup.failed': '启动检查失败',
};
const fr: Dictionary = { ...en, 'app.ready': 'OAT prêt', 'app.setup': 'Configurer OAT', 'app.settings': 'Paramètres', 'app.theme': 'Thème', 'app.language': 'Langue', 'theme.system': 'Système', 'theme.light': 'Clair', 'theme.dark': 'Sombre', 'settings.title': 'Paramètres', 'settings.general': 'Préférences de l’application', 'settings.globalConfig': 'Configuration globale', 'settings.models': 'Configuration des modèles', 'settings.save': 'Enregistrer', 'settings.saved': 'Enregistré', 'settings.failed': 'Échec de l’enregistrement', 'workspace.back': 'Espace de travail', 'workspace.operate': 'Exécuter', 'workspace.insights': 'Analyses', 'workspace.configure': 'Configurer', 'workspace.tasks': 'File de tâches', 'workspace.monitor': 'Activité en direct', 'workspace.usage': 'Utilisation', 'workspace.achievements': 'Résultats', 'workspace.config': 'Configuration d’équipe', 'workspace.resources': 'Ressources Agent', 'workspace.plugins': 'Extensions', 'workspace.channels': 'Canaux', 'resource.history': 'Historique des conversations', 'resource.projects': 'PROJETS', 'resource.thinking': 'Réflexion…', 'chat.you': 'Vous', 'chat.startAdmin': 'Commencer avec l’administrateur', 'chat.report': 'Flux de rapports Agent', 'chat.addContext': 'Ajouter du contexte', 'chat.approval': 'Demander une approbation', 'chat.voice': 'Entrée vocale', 'chat.send': 'Envoyer', 'queue.queued': 'En attente', 'queue.drag': 'Glisser pour réordonner', 'queue.delete': 'Supprimer la tâche', 'status.available': 'Disponible', 'status.busy': 'Occupé', 'status.offline': 'Hors ligne', 'status.running': 'En cours', 'status.completed': 'Terminé', 'status.failed': 'Échec', 'agent.none': 'Aucun Agent sélectionné', 'agent.inbox': 'Boîte de tâches', 'agent.reportOnly': 'Rapports uniquement', 'agent.taskProgress': 'Progression', 'agent.workQueue': 'File de travail', 'agent.allowed': 'Informations autorisées', 'agent.policy': 'Politique d’interaction', 'agent.project': 'Projet', 'agent.model': 'Modèle', 'agent.workspace': 'Espace de travail', 'agent.repositories': 'Dépôts', 'agent.skills': 'Compétences', 'agent.access': 'Accès', 'loading': 'Chargement des données locales…' };
const ja: Dictionary = { ...en, 'app.ready': 'OAT 準備完了', 'app.setup': 'OAT を設定', 'app.settings': '設定', 'app.theme': 'テーマ', 'app.language': '言語', 'theme.system': 'システム', 'theme.light': 'ライト', 'theme.dark': 'ダーク', 'settings.title': '設定', 'settings.general': 'アプリの設定', 'settings.globalConfig': 'グローバル設定', 'settings.models': 'グローバルモデル設定', 'settings.save': '保存', 'settings.saved': '保存しました', 'settings.failed': '保存に失敗しました', 'workspace.back': 'ワークスペース', 'workspace.operate': '操作', 'workspace.insights': '分析', 'workspace.configure': '構成', 'workspace.tasks': 'タスクキュー', 'workspace.monitor': 'ライブアクティビティ', 'workspace.usage': '使用量', 'workspace.achievements': '成果', 'workspace.config': 'チーム設定', 'workspace.resources': 'Agent リソース', 'workspace.plugins': 'プラグイン', 'workspace.channels': 'チャネル', 'resource.history': '会話履歴', 'resource.projects': 'プロジェクト', 'resource.thinking': '思考中…', 'chat.you': 'あなた', 'chat.startAdmin': '管理者との会話を開始', 'chat.report': 'Agent レポート', 'chat.addContext': 'コンテキストを追加', 'chat.approval': '承認を依頼', 'chat.voice': '音声入力', 'chat.send': '送信', 'queue.queued': '待機中', 'queue.drag': 'ドラッグして並べ替え', 'queue.delete': '待機中のタスクを削除', 'status.available': '利用可能', 'status.busy': '処理中', 'status.offline': 'オフライン', 'status.running': '実行中', 'status.completed': '完了', 'status.failed': '失敗', 'agent.none': 'Agent が選択されていません', 'agent.inbox': 'タスク受信箱', 'agent.reportOnly': 'レポートのみ', 'agent.taskProgress': 'タスクの進捗', 'agent.workQueue': '作業キュー', 'agent.allowed': '許可された情報', 'agent.policy': '操作ポリシー', 'agent.project': 'プロジェクト', 'agent.model': 'モデル', 'agent.workspace': 'ワークスペース', 'agent.repositories': 'リポジトリ', 'agent.skills': 'スキル', 'agent.access': 'アクセス', 'loading': 'ローカル制御データを読み込み中…' };
Object.assign(fr, { 'resource.agent': 'Responsable des ressources Agent' });
Object.assign(ja, { 'resource.agent': 'エージェントリソース管理者' });
Object.assign(fr, { 'git.title': 'Livraison Git', 'git.refresh': 'Actualiser l’état Git', 'git.startProject': 'Démarrez le projet pour inspecter les branches Agent et modifier Git.', 'git.remoteEnabled': 'publication activée', 'git.remoteDisabled': 'publication désactivée', 'git.localOnly': 'Git local uniquement', 'git.identityValid': 'Identité locale valide', 'git.identityMissing': 'Identité locale incomplète', 'git.merged': 'fusionné', 'git.pushed': 'poussé', 'git.dirty': 'non validé', 'git.clean': 'propre', 'git.notMerged': 'non fusionné', 'git.configure': 'Paramètres locaux et distants', 'git.remoteName': 'Nom distant (facultatif)', 'git.remoteUrl': 'URL distante (facultative)', 'git.userName': 'Nom utilisateur Git', 'git.userEmail': 'E-mail utilisateur Git', 'git.enablePush': 'Activer la publication distante', 'git.adminOnly': 'Seul Admin peut pousser explicitement une version fusionnée. Les identifiants restent dans SSH Agent ou le gestionnaire Git.', 'git.save': 'Enregistrer Git', 'git.saving': 'Enregistrement…' });
Object.assign(ja, { 'git.title': 'Git 配信状態', 'git.refresh': 'Git 状態を更新', 'git.startProject': 'プロジェクトを開始すると Agent のブランチ確認と Git 設定の変更ができます。', 'git.remoteEnabled': 'リモート公開有効', 'git.remoteDisabled': 'リモート公開無効', 'git.localOnly': 'ローカル Git のみ', 'git.identityValid': 'ローカル ID は有効', 'git.identityMissing': 'ローカル ID が不完全', 'git.merged': 'マージ済み', 'git.pushed': 'push 済み', 'git.dirty': '未コミット', 'git.clean': 'クリーン', 'git.notMerged': '未マージ', 'git.configure': 'ローカルとリモートの設定', 'git.remoteName': 'リモート名（任意）', 'git.remoteUrl': 'リモート URL（任意）', 'git.userName': 'Git ユーザー名', 'git.userEmail': 'Git ユーザーメール', 'git.enablePush': 'リモート公開を有効化', 'git.adminOnly': 'マージ済みリリースを明示的に push できるのは Admin のみです。認証情報は SSH Agent または Git credential helper で管理します。', 'git.save': 'Git 設定を保存', 'git.saving': '保存中…' });
Object.assign(fr, { 'workspace.docker': 'Runtime Docker', 'docker.title': 'Runtime Docker', 'docker.subtitle': 'Inspecter et gérer en sécurité les conteneurs Agent OAT.', 'docker.refresh': 'Actualiser', 'docker.engine': 'Moteur Docker', 'docker.available': 'Disponible', 'docker.unavailable': 'Indisponible', 'docker.runtime': 'Runtime du projet', 'docker.isolated': 'Isolation Docker', 'docker.localProcess': 'Isolation par processus local', 'docker.locked': 'Docker est définitivement requis', 'docker.canMigrate': 'Migration unidirectionnelle disponible', 'docker.containers': 'Conteneurs gérés', 'docker.running': 'actifs', 'docker.configuration': 'Configuration Docker', 'docker.migrate': 'Migrer vers Docker', 'docker.noDowngrade': 'L’image, le réseau et les limites restent modifiables, sans retour aux processus locaux.', 'docker.migrateHint': 'La migration redémarre le projet et est irréversible.', 'docker.image': 'Image', 'docker.network': 'Réseau', 'docker.extraArgs': 'Limites et durcissement', 'docker.safeArgs': 'Seules les limites de ressources et les options de durcissement sûres sont autorisées.', 'docker.saving': 'Enregistrement…', 'docker.saveRestart': 'Enregistrer et redémarrer', 'docker.migrateRestart': 'Migrer et redémarrer', 'docker.managedContainers': 'Conteneurs Agent', 'docker.status': 'État', 'docker.logs': 'Journaux', 'docker.restartAgent': 'Redémarrer l’Agent inactif', 'docker.restarting': 'Redémarrage…', 'docker.noContainers': 'Aucun conteneur Agent géré en cours.', 'docker.migrateToManage': 'Migrez vers Docker pour gérer les conteneurs Agent.', 'docker.close': 'Fermer', 'docker.noLogs': 'Aucun journal.', 'docker.migrationConfirm': 'Migrer ce projet vers Docker ? Le redémarrage est irréversible.' });
Object.assign(ja, { 'workspace.docker': 'Docker ランタイム', 'docker.title': 'Docker ランタイム', 'docker.subtitle': 'OAT Agent コンテナを安全に確認・管理します。', 'docker.refresh': '更新', 'docker.engine': 'Docker Engine', 'docker.available': '利用可能', 'docker.unavailable': '利用不可', 'docker.runtime': 'プロジェクトランタイム', 'docker.isolated': 'Docker 分離', 'docker.localProcess': 'ローカルプロセス分離', 'docker.locked': 'Docker 分離が恒久的に必要です', 'docker.canMigrate': 'Docker への一方向移行が可能です', 'docker.containers': '管理対象コンテナ', 'docker.running': '実行中', 'docker.configuration': 'Docker 設定', 'docker.migrate': 'Docker へ移行', 'docker.noDowngrade': 'イメージ、ネットワーク、制限は変更できますがローカルプロセスへ戻せません。', 'docker.migrateHint': '移行はプロジェクトを再起動し、元に戻せません。', 'docker.image': 'イメージ', 'docker.network': 'ネットワーク', 'docker.extraArgs': 'リソース・強化設定', 'docker.safeArgs': '安全なリソース制限と強化オプションのみ使用できます。', 'docker.saving': '保存中…', 'docker.saveRestart': '保存して再起動', 'docker.migrateRestart': '移行して再起動', 'docker.managedContainers': 'Agent コンテナ', 'docker.status': '状態', 'docker.logs': 'ログ', 'docker.restartAgent': '待機中 Agent を再起動', 'docker.restarting': '再起動中…', 'docker.noContainers': '実行中の管理対象 Agent コンテナはありません。', 'docker.migrateToManage': 'Docker へ移行すると Agent コンテナを管理できます。', 'docker.close': '閉じる', 'docker.noLogs': 'ログはありません。', 'docker.migrationConfirm': 'Docker 分離へ移行しますか？再起動後は元に戻せません。' });
Object.assign(fr, { 'docker.remove': 'Supprimer l’orphelin', 'docker.removeConfirm': 'Supprimer ce conteneur OAT arrêté ou orphelin ?' });
Object.assign(ja, { 'docker.remove': '孤立コンテナを削除', 'docker.removeConfirm': '停止済みまたは孤立した OAT コンテナを削除しますか？' });
Object.assign(en, { 'docker.notInstalled': 'Docker is not installed', 'docker.daemonStopped': 'Docker Engine is stopped', 'docker.daemonStoppedHint': 'Docker is installed locally. Start its engine before migrating or running Agent containers.', 'docker.install': 'Install Docker', 'docker.installing': 'Installing Docker…', 'docker.installConfirm': 'Install Docker on this computer now? The installer may download software, request administrator approval, and requires acceptance of Docker’s terms and applicable licensing.', 'docker.installNotice': 'Docker is required for container isolation. Installation starts only after your confirmation and may request system authorization. Review Docker’s terms and licensing before continuing.', 'docker.installGuide': 'Official installation guide', 'docker.start': 'Start Docker', 'docker.starting': 'Starting Docker…' });
Object.assign(zh, { 'docker.notInstalled': '本地未安装 Docker', 'docker.daemonStopped': 'Docker Engine 未启动', 'docker.daemonStoppedHint': '已检测到本地 Docker。迁移或运行 Agent 容器前，请先启动 Docker Engine。', 'docker.install': '安装 Docker', 'docker.installing': '正在安装 Docker…', 'docker.installConfirm': '现在在这台电脑上安装 Docker 吗？安装程序可能会下载软件、请求管理员授权，并要求你接受 Docker 的条款及适用许可。', 'docker.installNotice': '容器隔离需要 Docker。只有在你确认后才会开始安装，期间可能请求系统授权；继续前请查看 Docker 的条款与许可。', 'docker.installGuide': '官方安装指南', 'docker.start': '启动 Docker', 'docker.starting': '正在启动 Docker…' });
Object.assign(fr, { 'docker.notInstalled': 'Docker n’est pas installé', 'docker.daemonStopped': 'Docker Engine est arrêté', 'docker.daemonStoppedHint': 'Docker est installé localement. Démarrez son moteur avant toute migration ou exécution de conteneurs Agent.', 'docker.install': 'Installer Docker', 'docker.installing': 'Installation de Docker…', 'docker.installConfirm': 'Installer Docker sur cet ordinateur maintenant ? Le programme peut télécharger des logiciels, demander une autorisation administrateur et exige l’acceptation des conditions et licences Docker.', 'docker.installNotice': 'Docker est requis pour l’isolation par conteneurs. L’installation ne démarre qu’après votre confirmation et peut demander une autorisation système.', 'docker.installGuide': 'Guide d’installation officiel', 'docker.start': 'Démarrer Docker', 'docker.starting': 'Démarrage de Docker…' });
Object.assign(ja, { 'docker.notInstalled': 'Docker がインストールされていません', 'docker.daemonStopped': 'Docker Engine が停止しています', 'docker.daemonStoppedHint': 'Docker はローカルにインストール済みです。移行や Agent コンテナの実行前に Engine を起動してください。', 'docker.install': 'Docker をインストール', 'docker.installing': 'Docker をインストール中…', 'docker.installConfirm': 'このコンピューターに Docker をインストールしますか？ソフトウェアのダウンロードや管理者承認が必要になる場合があり、Docker の規約と適用ライセンスへの同意が必要です。', 'docker.installNotice': 'コンテナ分離には Docker が必要です。確認後にのみインストールを開始し、システム承認を求める場合があります。', 'docker.installGuide': '公式インストールガイド', 'docker.start': 'Docker を起動', 'docker.starting': 'Docker を起動中…' });
Object.assign(en, { 'docker.permissionDenied': 'Docker Engine access denied', 'docker.permissionDeniedHint': 'Docker is installed, but this user cannot access its daemon. Restart Docker Desktop or apply the required Docker socket/group permission, then try again.' });
Object.assign(zh, { 'docker.permissionDenied': '无权访问 Docker Engine', 'docker.permissionDeniedHint': 'Docker 已安装，但当前用户无法访问 daemon。请重启 Docker Desktop，或配置所需的 Docker socket/用户组权限后重试。' });
Object.assign(fr, { 'docker.permissionDenied': 'Accès à Docker Engine refusé', 'docker.permissionDeniedHint': 'Docker est installé, mais cet utilisateur ne peut pas accéder au daemon. Redémarrez Docker Desktop ou corrigez les permissions du socket/groupe Docker.' });
Object.assign(ja, { 'docker.permissionDenied': 'Docker Engine へのアクセスが拒否されました', 'docker.permissionDeniedHint': 'Docker はインストール済みですが、このユーザーは daemon にアクセスできません。Docker Desktop を再起動するか、Docker socket／グループ権限を設定してください。' });
Object.assign(fr, { 'startup.services': 'Initialisation des services Desktop…', 'startup.oat': 'Outil OAT', 'startup.docker': 'Environnement Docker', 'startup.desktopServices': 'Services Desktop', 'startup.pending': 'En attente de vérification', 'startup.checkingNode': 'Vérification de la compatibilité Node.js…', 'startup.checkingOat': 'Vérification de l’outil OAT…', 'startup.checkingDocker': 'Vérification de l’environnement Docker local…', 'startup.installingNode': 'Installation d’un runtime Node.js géré…', 'startup.installingOat': 'Installation de l’outil OAT…', 'startup.nodeUnavailable': 'Aucun runtime Node.js compatible n’est disponible.', 'startup.oatUnavailable': 'L’outil OAT n’est pas disponible.', 'startup.dockerNotInstalled': 'Non installé · configurable plus tard dans la gestion Docker', 'startup.dockerStopped': 'Installé · Docker Engine n’est pas démarré', 'startup.dockerPermission': 'Installé · l’accès au daemon nécessite une intervention', 'startup.dockerDeferred': 'Vérification indisponible · configurable plus tard' });
Object.assign(ja, { 'startup.services': 'Desktop サービスを初期化中…', 'startup.oat': 'OAT ツール', 'startup.docker': 'Docker 環境', 'startup.desktopServices': 'Desktop サービス', 'startup.pending': '確認待ち', 'startup.checkingNode': 'Node.js の互換性を確認中…', 'startup.checkingOat': 'OAT コマンドラインツールを確認中…', 'startup.checkingDocker': 'ローカル Docker 環境を確認中…', 'startup.installingNode': '管理対象 Node.js ランタイムをインストール中…', 'startup.installingOat': 'OAT ツールをインストール中…', 'startup.nodeUnavailable': '互換性のある Node.js ランタイムを利用できません。', 'startup.oatUnavailable': 'OAT ツールを利用できません。', 'startup.dockerNotInstalled': '未インストール · Docker 管理で後から設定できます', 'startup.dockerStopped': 'インストール済み · Docker Engine は停止中です', 'startup.dockerPermission': 'インストール済み · daemon アクセス権限の確認が必要です', 'startup.dockerDeferred': '確認できません · Docker 管理で後から設定できます' });
const dictionaries: Record<Language, Dictionary> = { 'zh-CN': zh, en, fr, ja };

type Theme = 'system' | 'light' | 'dark';
type I18n = { language: Language; setLanguage(language: Language): void; theme: Theme; setTheme(theme: Theme): void; t(key: string): string };
const I18nContext = createContext<I18n | undefined>(undefined);
export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('oat.language') as Language) || 'zh-CN');
  const [theme, setTheme] = useState<Theme>(() => (localStorage.getItem('oat.theme') as Theme) || 'system');
  useEffect(() => { localStorage.setItem('oat.language', language); document.documentElement.lang = language; }, [language]);
  useEffect(() => { localStorage.setItem('oat.theme', theme); const dark = theme === 'dark' || (theme === 'system' && matchMedia('(prefers-color-scheme: dark)').matches); document.documentElement.dataset.theme = dark ? 'dark' : 'light'; }, [theme]);
  const value = useMemo<I18n>(() => ({ language, setLanguage, theme, setTheme, t: (key) => dictionaries[language][key] ?? en[key] ?? key }), [language, theme]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n(): I18n { const context = useContext(I18nContext); if (!context) throw new Error('I18nProvider is missing.'); return context; }
