import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'zh-CN' | 'en' | 'fr' | 'ja';
type Dictionary = Record<string, string>;
const en: Dictionary = {
  'app.ready': 'OAT ready', 'app.setup': 'OAT setup', 'app.settings': 'Settings', 'app.theme': 'Theme', 'app.language': 'Language', 'theme.system': 'System', 'theme.light': 'Light', 'theme.dark': 'Dark',
  'header.collapseResources': 'Collapse resources', 'header.showResources': 'Show resources', 'header.refresh': 'Refresh workspace', 'header.collapseDetails': 'Collapse agent details', 'header.showDetails': 'Show agent details',
  'settings.title': 'Settings', 'settings.general': 'Application preferences', 'settings.globalConfig': 'Global configuration', 'settings.models': 'Global model configuration', 'settings.save': 'Save configuration', 'settings.saved': 'Saved', 'settings.failed': 'Save failed',
  'workspace.back': 'Workspace', 'workspace.operate': 'Operate', 'workspace.insights': 'Insights', 'workspace.configure': 'Configure', 'workspace.tasks': 'Task queue', 'workspace.monitor': 'Live activity', 'workspace.docker': 'Docker runtime', 'workspace.usage': 'Usage', 'workspace.achievements': 'Achievements', 'workspace.config': 'Team config', 'workspace.resources': 'Agent resources', 'workspace.plugins': 'Plugins', 'workspace.channels': 'Channels', 'workspace.settings': 'Settings',
  'taskPanel.title': 'Task board', 'taskPanel.live': 'LIVE · refreshes every 3 seconds', 'taskPanel.empty': 'No tasks have been created for this project.', 'taskPanel.emptyColumn': 'No tasks in this status.', 'taskPanel.progress': 'Progress', 'taskPanel.backlog': 'Backlog', 'taskPanel.active': 'In progress', 'taskPanel.waiting': 'Waiting / paused', 'taskPanel.done': 'Done', 'taskPanel.attention': 'Needs attention', 'taskPanel.pause': 'Pause', 'taskPanel.resume': 'Resume', 'taskPanel.snapshots': 'Snapshots', 'taskPanel.blocked': 'Queue blocker', 'taskPanel.recalledFrom': 'Recalled from', 'taskPanel.pauseSuccess': 'Task paused', 'taskPanel.resumeSuccess': 'Task resumed', 'taskPanel.latestDelivery': 'Latest delivery', 'taskPanel.latestProgress': 'Latest progress', 'taskPanel.errorDetail': 'Error', 'taskPanel.viewFull': 'View full details',
  'ops.noTasks': 'No tasks yet.', 'ops.agent': 'Agent', 'ops.task': 'Task', 'ops.status': 'Status', 'ops.readOnlyTitle': 'Tasks start only through the Admin conversation', 'ops.readOnlyHint': 'Select the Admin and describe the outcome. The Admin plans and delegates work; this page only displays execution state.', 'ops.activityEyebrow': 'PROJECT ACTIVITY', 'ops.tasksSubtitle': 'Review the task queue and execution results.', 'ops.totalTasks': 'Total tasks', 'ops.queue': 'Task queue', 'ops.recentOrder': 'Sorted by most recent update', 'ops.readOnly': 'Read only', 'ops.noTopology': 'No topology data.', 'ops.noOutput': 'No log output', 'ops.notStarted': 'Not started', 'ops.zoomOut': 'Zoom out', 'ops.resetTopology': 'Reset topology view', 'ops.reset': 'Reset', 'ops.zoomIn': 'Zoom in', 'ops.panZoom': 'Drag to pan · scroll to zoom', 'ops.monitorEyebrow': 'LIVE ACTIVITY', 'ops.monitorSubtitle': 'Track team status, progress, and events.', 'ops.connected': 'Live connection', 'ops.reconnecting': 'Reconnecting', 'ops.topology': 'Agent topology', 'ops.topologyHint': 'Inspect collaboration relationships. Detailed processing stays in the Agent conversation thinking area.', 'ops.latestProgress': 'Latest progress', 'ops.progressHint': 'Milestone reports from the team.', 'ops.noProgress': 'No progress reports yet.', 'ops.recentTasks': 'Recent tasks', 'ops.tasksByUpdate': 'tasks, sorted by update time.', 'ops.liveEvents': 'Live events', 'ops.eventsHint': 'Filter Orchestrator and Agent execution records.', 'ops.allTeams': 'All teams', 'ops.allSources': 'All sources', 'ops.filterPlaceholder': 'Filter events, Agent, or content', 'ops.waitingEvents': 'Waiting for events…',
  'resource.title': 'AGENTIC RESOURCES', 'resource.agent': 'Agent Resources Manager', 'resource.history': 'Conversation history', 'resource.projects': 'PROJECTS', 'resource.thinking': 'Thinking…', 'resource.noProjects': 'No projects are registered.', 'resource.historyTitle': 'Agent Resources Manager history', 'resource.historyText': 'Record organization, team, Agent and workspace management requests.', 'resource.placeholder': 'Ask the Agent Resources Manager about projects or Agent resources…', 'resource.steward': 'Local organization steward', 'resource.scope': 'Scope', 'resource.scopeAccess': 'Projects, team configuration, Agent resources and workspace permissions.', 'resource.taskPolicy': 'Does not receive project work; project Admins own task intake.',
  'resources.eyebrow': 'AGENT RESOURCES', 'resources.title': 'Build a project organization', 'resources.hint': 'Create an Admin, independent team Leaders, and self-testing Workers. All model choices come from the global model catalog.', 'resources.targetProject': 'Save to registered project', 'resources.currentProject': 'Current/default project', 'resources.productionBranch': 'Production branch', 'resources.runtime': 'Runtime', 'resources.addTeam': 'Add independent team', 'resources.generate': 'Generate and save organization', 'resources.responsibilityDefault': 'Plan independent work, review branches, integrate approved changes, and submit releases.', 'resources.teamRequired': 'At least one team is required.', 'resources.requiredFields': 'Complete the required project and team fields.', 'resources.saved': 'Organization configuration saved.',
  'chat.you': 'You', 'chat.team': 'Open Agent Team', 'chat.startAdmin': 'Start with the Admin', 'chat.report': 'Agent report feed', 'chat.messageAdmin': 'Message project Admin…', 'chat.addContext': 'Add context', 'chat.approval': 'Request approval', 'chat.voice': 'Voice input', 'chat.admin': 'Local Admin', 'chat.configureModel': 'Configure agent model', 'chat.send': 'Send', 'chat.stop': 'Stop request', 'chat.execution': 'Agent execution', 'chat.live': 'LIVE', 'chat.processing': 'Processing', 'chat.processed': 'Processed', 'chat.seconds': 's', 'chat.thinking': 'Latest reasoning and events',
  'chat.noModels': 'No global models configured', 'chat.currentModel': 'Current configuration', 'chat.chooseModel': 'Choose a global model',
  'queue.queued': 'Queued', 'queue.drag': 'Drag to reorder', 'queue.delete': 'Delete queued task',
  'status.available': 'Available', 'status.busy': 'Busy', 'status.offline': 'Offline', 'status.attention': 'Needs attention', 'status.queued': 'Queued', 'status.paused': 'Paused', 'status.waiting': 'Waiting for delegated work', 'status.running': 'Running', 'status.review_pending': 'Awaiting review', 'status.completed': 'Completed', 'status.cancelled': 'Cancelled', 'status.failed': 'Failed',
  'agent.none': 'No agent selected', 'agent.choose': 'Choose a project and an Agent from Agentic resources.', 'agent.inbox': 'Task inbox', 'agent.reportOnly': 'Report-only', 'agent.taskProgress': 'Task progress', 'agent.workQueue': 'Work queue', 'agent.noTask': 'No active task assigned.', 'agent.noQueue': 'No queued work.', 'agent.executing': 'Executing now', 'agent.queued': 'Queued for execution', 'agent.awaiting': 'Awaiting new work', 'agent.allowed': 'Allowed information', 'agent.policy': 'Interaction policy', 'agent.project': 'Project', 'agent.model': 'Model', 'agent.workspace': 'Workspace', 'agent.repositories': 'Repositories', 'agent.skills': 'Skills', 'agent.access': 'Access', 'agent.defaultModel': 'Project default', 'agent.projectWorkspace': 'Project workspace', 'agent.noSkills': 'No explicit skills', 'agent.adminAccess': 'Accepts new task requests for this project.', 'agent.readOnlyAccess': 'Read-only reports and execution status. New tasks must go through Admin.', 'agent.tasks': 'tasks', 'agent.delegated': 'Delegated Agents', 'agent.delegatedHint': 'Tasks sent by this Agent',
  'workspaceFiles.open': 'Browse Agent workspace', 'workspaceFiles.title': 'Agent workspace files', 'workspaceFiles.readOnly': 'READ ONLY', 'workspaceFiles.root': 'Workspace', 'workspaceFiles.startProject': 'Start the project to browse this Agent workspace.', 'workspaceFiles.empty': 'This directory is empty.', 'workspaceFiles.selectFile': 'Select a file to preview.', 'workspaceFiles.binary': 'Binary files cannot be previewed.', 'workspaceFiles.tooLarge': 'This file is larger than the 512 KB preview limit.',
  'git.title': 'Git delivery', 'git.refresh': 'Refresh Git status', 'git.startProject': 'Start the project to inspect Agent branches and edit Git settings.', 'git.remoteEnabled': 'publishing enabled', 'git.remoteDisabled': 'publishing disabled', 'git.localOnly': 'Local Git only', 'git.identityValid': 'Valid local identity', 'git.identityMissing': 'Local identity incomplete', 'git.merged': 'merged', 'git.pushed': 'pushed', 'git.dirty': 'uncommitted', 'git.clean': 'clean', 'git.notMerged': 'not merged', 'git.configure': 'Local and remote settings', 'git.remoteName': 'Remote name (optional)', 'git.remoteUrl': 'Remote URL (optional)', 'git.userName': 'Git user name', 'git.userEmail': 'Git user email', 'git.enablePush': 'Enable remote publishing', 'git.adminOnly': 'Only Admin can explicitly push a merged release. Credentials stay in SSH Agent or the Git credential helper.', 'git.save': 'Save Git settings', 'git.saving': 'Saving…',
  'docker.title': 'Docker runtime', 'docker.subtitle': 'Inspect and safely manage OAT Agent containers.', 'docker.refresh': 'Refresh', 'docker.engine': 'Docker Engine', 'docker.available': 'Available', 'docker.unavailable': 'Unavailable', 'docker.runtime': 'Project runtime', 'docker.isolated': 'Docker isolation', 'docker.localProcess': 'Local process isolation', 'docker.locked': 'Docker isolation is permanently required', 'docker.canMigrate': 'One-way migration to Docker is available', 'docker.containers': 'Managed containers', 'docker.running': 'running', 'docker.configuration': 'Docker configuration', 'docker.migrate': 'Migrate runtime to Docker', 'docker.noDowngrade': 'Image, network, and limits can change, but Docker cannot be changed back to local processes.', 'docker.migrateHint': 'Migration restarts the project and is irreversible.', 'docker.image': 'Image', 'docker.network': 'Network', 'docker.extraArgs': 'Resource and hardening flags', 'docker.safeArgs': 'Allowed: CPU/memory/PID/ulimit/tmpfs limits, read-only, cap-drop=ALL, and no-new-privileges.', 'docker.saving': 'Saving…', 'docker.saveRestart': 'Save and restart project', 'docker.migrateRestart': 'Migrate and restart project', 'docker.managedContainers': 'Agent containers', 'docker.status': 'Status', 'docker.logs': 'Logs', 'docker.restartAgent': 'Restart idle Agent', 'docker.restarting': 'Restarting…', 'docker.noContainers': 'No managed Agent containers are currently running.', 'docker.migrateToManage': 'Migrate this project to Docker to manage Agent containers.', 'docker.close': 'Close', 'docker.noLogs': 'No log output.', 'docker.migrationConfirm': 'Migrate this project to Docker isolation? This restarts the project and cannot be reversed.',
  'docker.remove': 'Remove orphan', 'docker.removeConfirm': 'Remove this stopped or orphaned OAT container?',
  'time.second': 's', 'time.minute': 'm', 'time.hour': 'h', 'time.day': 'd',
  'management.eyebrow': 'DECLARATIVE CONTROL', 'management.title': 'Configuration & models', 'management.refresh': 'Refresh', 'management.teamConfig': 'Project team configuration', 'management.teamConfigHint': 'This page follows the selected Agent in the sidebar. Shared project settings remain available above the selected team settings.', 'management.project': 'Project', 'management.team': 'Team', 'management.projectScope': 'Project settings', 'management.adminScope': 'Administrator settings', 'management.administrator': 'Administrator', 'management.saved': 'Saved', 'management.unsavedDraft': 'Unsaved draft', 'management.chooseModel': 'Choose a model', 'management.inheritDefault': 'Inherit default', 'management.addTeam': 'Add independent team', 'management.reloadFields': 'Reload structured fields from JSON', 'management.discardDraft': 'Discard local draft', 'management.modelsProviders': 'Models & providers', 'management.modelsProvidersHint': 'Project aliases are used by every model selector below. Provider keys, URLs and test-only credentials remain in team.json.', 'management.removeProvider': 'Remove provider', 'management.providerKey': 'Provider key', 'management.protocol': 'Protocol', 'management.compatible': 'compatible', 'management.baseUrl': 'Base URL', 'management.apiKey': 'API key', 'management.noProviders': 'No project providers configured.', 'management.addProvider': 'Add provider', 'management.syncModels': 'Fetch & sync all models', 'management.modelAliases': 'Model aliases', 'management.addAlias': 'Add alias', 'management.alias': 'Alias', 'management.providerModelId': 'Provider model ID', 'management.remove': 'Remove', 'management.noAliases': 'No aliases configured.',
  'management.addSkill': 'Add skill', 'management.skillSource': 'Skill source', 'management.skillNames': 'Skill names', 'management.skillHint': 'Comma-separated skill names.', 'management.noSkills': 'No skills configured.', 'management.teamIdentifier': 'Team identifier', 'management.branchPrefix': 'Branch prefix', 'management.leaderName': 'Leader name', 'management.leaderModel': 'Leader model', 'management.leaderResponsibility': 'Leader responsibility', 'management.leaderPrompt': 'Leader prompt', 'management.leaderRepos': 'Allowed repositories / paths', 'management.reposHint': 'Comma-separated repository names or paths.', 'management.leaderSkills': 'Leader skills', 'management.workerCount': 'Worker count', 'management.workerModel': 'Worker model', 'management.workerPrompt': 'Worker prompt', 'management.skillSync': 'Skill synchronization', 'management.inheritInject': 'Inherit and inject on spawn', 'management.manual': 'Manual', 'management.workerSkills': 'Worker skills', 'management.noSelectedTeam': 'No matching team was found for the selected Agent.',
  'management.projectRuntimeWorkspace': 'Shared project, runtime & workspace', 'management.projectRuntimeWorkspaceHint': 'These values are shared by all Agents in the selected project.', 'management.projectName': 'Project name', 'management.repositoryPath': 'Repository path', 'management.baseBranch': 'Base branch', 'management.defaultModel': 'Default model', 'management.runtimeMode': 'Runtime mode', 'management.localProcess': 'Local process', 'management.dockerSandbox': 'Docker sandbox', 'management.dockerLocked': 'Docker isolation is permanently required for this project.', 'management.dockerMigrationHint': 'Migration to Docker is one-way and restarts the project.', 'management.stateDirectory': 'State directory', 'management.dockerImage': 'Docker image', 'management.dockerNetwork': 'Docker network', 'management.dockerArgs': 'Docker extra arguments', 'management.dockerArgsHint': 'Comma-separated arguments.', 'management.workspaceProvider': 'Workspace provider', 'management.worktree': 'Worktree', 'management.sharedClone': 'Shared clone', 'management.fullClone': 'Full clone', 'management.workspaceRoot': 'Workspace root', 'management.gitRemote': 'Git remote', 'management.gitRemoteUrl': 'Git remote URL', 'management.gitUserName': 'Git user name', 'management.gitUserEmail': 'Git user email', 'management.adminPush': 'Enable Admin remote push', 'management.gitLfs': 'Git LFS', 'management.pull': 'pull', 'management.skip': 'skip', 'management.allowPullDenyChange': 'allow pull, deny change', 'management.sparseCheckout': 'Sparse checkout', 'management.adminName': 'Admin name', 'management.adminModel': 'Admin model', 'management.adminDescription': 'Admin description', 'management.adminPrompt': 'Admin prompt', 'management.save': 'Save project configuration', 'management.restartProject': 'Restart selected project',
  'management.globalModelCatalog': 'Global model catalog', 'management.globalModelCatalogHint': 'Model availability is managed only in Global Settings. This project stores selections, not providers or registry entries.', 'management.savedMessage': 'Project configuration saved.',
  'settings.eyebrow': 'GLOBAL CONTROL', 'settings.subtitle': 'Manage shared preferences and the model registry for this Desktop.', 'settings.retention': 'Log retention', 'settings.retentionHint': 'Keep observability logs from 1 to 365 days.', 'settings.retentionDays': 'Log retention days', 'settings.saveRetention': 'Save retention', 'settings.registry': 'Global model registry', 'settings.registryHint': 'Shared models are available to every project. Removing an entry does not change existing team.json declarations.', 'settings.provider': 'Provider', 'settings.key': 'Key', 'settings.actions': 'Actions', 'settings.configured': 'configured', 'settings.noProviders': 'No providers configured.', 'settings.noModels': 'No models registered.', 'settings.modelAlias': 'Model alias', 'settings.providerModel': 'Provider model', 'settings.copy': 'Copy', 'settings.clearRegistry': 'Clear all providers and models', 'settings.advanced': 'Advanced global configuration', 'settings.advancedHint': 'Edit only when you need settings that are not represented above.', 'settings.saveGlobal': 'Save global configuration',
  'settings.providerName': 'Provider name', 'settings.testApiKey': 'API key for connection test', 'settings.connectProvider': 'Test connection and synchronize models',
  'error.startProject': 'This view is available after the project starts.', 'loading': 'Loading local control-plane data…',
  'startup.title': 'Initializing Open Agent Team', 'startup.subtitle': 'Preparing your local workspace.', 'startup.services': 'Initializing Desktop services…', 'startup.node': 'Node.js environment', 'startup.oat': 'OAT tool', 'startup.docker': 'Docker environment', 'startup.desktopServices': 'Desktop services', 'startup.pending': 'Waiting to check', 'startup.checking': 'Checking…', 'startup.checkingNode': 'Checking Node.js compatibility…', 'startup.checkingOat': 'Checking the OAT command-line tool…', 'startup.checkingDocker': 'Checking the local Docker environment…', 'startup.ready': 'Ready', 'startup.installing': 'Installing local runtime…', 'startup.installingNode': 'Installing a managed Node.js runtime…', 'startup.installingOat': 'Installing the OAT tool…', 'startup.nodeUnavailable': 'A compatible Node.js runtime is unavailable.', 'startup.oatUnavailable': 'The OAT tool is unavailable.', 'startup.dockerNotInstalled': 'Not installed · configure later in Docker management', 'startup.dockerStopped': 'Installed · Docker Engine is not running', 'startup.dockerPermission': 'Installed · daemon access requires attention', 'startup.dockerDeferred': 'Check unavailable · configure later in Docker management', 'startup.retry': 'Try again', 'startup.failed': 'Startup check failed',
};
const zh: Dictionary = { ...en,
  'app.ready': 'OAT 已就绪', 'app.setup': '配置 OAT', 'app.settings': '设置', 'app.theme': '主题', 'app.language': '语言', 'theme.system': '跟随系统', 'theme.light': '浅色', 'theme.dark': '深色',
  'header.collapseResources': '收起资源', 'header.showResources': '显示资源', 'header.refresh': '刷新工作区', 'header.collapseDetails': '收起 Agent 详情', 'header.showDetails': '显示 Agent 详情',
  'settings.title': '设置', 'settings.general': '应用偏好', 'settings.globalConfig': '全局配置', 'settings.models': '全局模型配置', 'settings.save': '保存配置', 'settings.saved': '已保存', 'settings.failed': '保存失败',
  'workspace.back': '工作区', 'workspace.operate': '运行', 'workspace.insights': '洞察', 'workspace.configure': '配置', 'workspace.tasks': '任务队列', 'workspace.monitor': '实时活动', 'workspace.docker': 'Docker 运行环境', 'workspace.usage': '用量', 'workspace.achievements': '成果', 'workspace.config': '团队配置', 'workspace.resources': 'Agent 资源', 'workspace.plugins': '插件', 'workspace.channels': '通道', 'workspace.settings': '设置',
  'taskPanel.title': '任务看板', 'taskPanel.live': '实时 · 每 3 秒刷新', 'taskPanel.empty': '该项目组暂未创建任务。', 'taskPanel.emptyColumn': '该状态暂无任务。', 'taskPanel.progress': '进度', 'taskPanel.backlog': '待处理', 'taskPanel.active': '进行中', 'taskPanel.waiting': '等待 / 已暂停', 'taskPanel.done': '已完成', 'taskPanel.attention': '需处理', 'taskPanel.pause': '暂停', 'taskPanel.resume': '继续', 'taskPanel.snapshots': '任务快照', 'taskPanel.blocked': '排队原因', 'taskPanel.recalledFrom': '恢复来源', 'taskPanel.pauseSuccess': '任务已暂停', 'taskPanel.resumeSuccess': '任务已继续', 'taskPanel.latestDelivery': '最新交付', 'taskPanel.latestProgress': '最新进度', 'taskPanel.errorDetail': '错误信息', 'taskPanel.viewFull': '查看完整内容',
  'ops.noTasks': '暂无任务。', 'ops.agent': 'Agent', 'ops.task': '任务', 'ops.status': '状态', 'ops.readOnlyTitle': '任务仅通过管理员对话发起', 'ops.readOnlyHint': '选择管理员并描述目标即可。管理员会规划并分派工作；此页面只展示执行状态。', 'ops.activityEyebrow': '项目活动', 'ops.tasksSubtitle': '查看任务队列与执行结果。', 'ops.totalTasks': '总任务', 'ops.queue': '任务队列', 'ops.recentOrder': '按最近更新时间排序', 'ops.readOnly': '只读', 'ops.noTopology': '暂无拓扑数据。', 'ops.noOutput': '没有日志输出', 'ops.notStarted': '未启动', 'ops.zoomOut': '缩小', 'ops.resetTopology': '重置拓扑视图', 'ops.reset': '重置', 'ops.zoomIn': '放大', 'ops.panZoom': '拖拽平移 · 滚动缩放', 'ops.monitorEyebrow': '实时活动', 'ops.monitorSubtitle': '跟踪团队运行状态、进度与事件。', 'ops.connected': '实时连接', 'ops.reconnecting': '正在重连', 'ops.topology': 'Agent 拓扑', 'ops.topologyHint': '查看协作关系；详细处理过程统一显示在 Agent 对话的思考区。', 'ops.latestProgress': '最新进度', 'ops.progressHint': '来自团队的阶段性汇报。', 'ops.noProgress': '暂无进度汇报。', 'ops.recentTasks': '最近任务', 'ops.tasksByUpdate': '个任务，按更新时间排序。', 'ops.liveEvents': '实时事件', 'ops.eventsHint': '筛选 Orchestrator 和 Agent 的运行记录。', 'ops.allTeams': '全部团队', 'ops.allSources': '全部来源', 'ops.filterPlaceholder': '筛选事件、Agent 或内容', 'ops.waitingEvents': '正在等待事件…',
  'resource.title': '智能资源', 'resource.agent': '智能体资源主管', 'resource.history': '会话记录', 'resource.projects': '项目', 'resource.thinking': '思考中…', 'resource.noProjects': '尚未注册项目。', 'resource.historyTitle': '智能体资源主管会话记录', 'resource.historyText': '用于记录组织、团队、Agent 与工作区管理请求。', 'resource.placeholder': '向智能体资源主管询问项目或 Agent 资源…', 'resource.steward': '本地组织管理员', 'resource.scope': '范围', 'resource.scopeAccess': '项目、团队配置、Agent 资源与工作区权限。', 'resource.taskPolicy': '不接收项目工作；项目 Admin 负责接收任务。',
  'resources.eyebrow': 'AGENT 资源', 'resources.title': '创建项目组织', 'resources.hint': '创建 Admin、独立团队组长和可自测的 Worker；所有模型选择统一来自全局模型目录。', 'resources.targetProject': '保存到已注册项目', 'resources.currentProject': '当前 / 默认项目', 'resources.productionBranch': '生产分支', 'resources.runtime': '运行环境', 'resources.addTeam': '添加独立团队', 'resources.generate': '生成并保存组织配置', 'resources.responsibilityDefault': '规划独立工作、评审分支、集成批准的变更并提交发布。', 'resources.teamRequired': '至少需要一个团队。', 'resources.requiredFields': '请填写完整的项目和团队必填字段。', 'resources.saved': '组织配置已保存。',
  'chat.you': '你', 'chat.startAdmin': '与管理员开始会话', 'chat.report': 'Agent 汇报', 'chat.messageAdmin': '向项目管理员发送消息…', 'chat.addContext': '添加上下文', 'chat.approval': '请求批准', 'chat.voice': '语音输入', 'chat.admin': '本地管理员', 'chat.configureModel': '配置 Agent 模型', 'chat.send': '发送', 'chat.stop': '停止请求', 'chat.execution': 'Agent 执行过程', 'chat.live': '实时', 'chat.processing': '正在处理', 'chat.processed': '已处理', 'chat.seconds': '秒', 'chat.thinking': '最新思考过程与处理事件', 'queue.queued': '排队中', 'queue.drag': '拖拽排序', 'queue.delete': '删除排队任务',
  'chat.noModels': '尚未配置全局模型', 'chat.currentModel': '当前配置', 'chat.chooseModel': '选择全局模型',
  'status.available': '可用', 'status.busy': '忙碌', 'status.offline': '离线', 'status.attention': '需要处理', 'status.queued': '排队中', 'status.paused': '已暂停', 'status.waiting': '等待下级任务', 'status.running': '执行中', 'status.review_pending': '等待组长评审', 'status.completed': '已完成', 'status.cancelled': '已取消', 'status.failed': '失败',
  'agent.none': '未选择 Agent', 'agent.choose': '请从智能资源中选择项目和 Agent。', 'agent.inbox': '任务入口', 'agent.reportOnly': '仅汇报', 'agent.taskProgress': '任务进度', 'agent.workQueue': '工作队列', 'agent.noTask': '暂无活跃任务。', 'agent.noQueue': '暂无排队工作。', 'agent.executing': '正在执行', 'agent.queued': '等待执行', 'agent.awaiting': '等待新任务', 'agent.allowed': '允许的信息', 'agent.policy': '交互策略', 'agent.project': '项目', 'agent.model': '模型', 'agent.workspace': '工作区', 'agent.repositories': '仓库', 'agent.skills': '技能', 'agent.access': '访问', 'agent.defaultModel': '项目默认模型', 'agent.projectWorkspace': '项目工作区', 'agent.noSkills': '没有显式技能', 'agent.adminAccess': '接收此项目的新任务请求。', 'agent.readOnlyAccess': '只读汇报和执行状态；新任务必须交给 Admin。', 'agent.tasks': '项任务', 'agent.delegated': '下发任务的 Agent', 'agent.delegatedHint': '由当前 Agent 下发', 'error.startProject': '启动项目后即可使用此视图。', 'loading': '正在加载本地控制面数据…',
  'workspaceFiles.open': '查看 Agent 工作区', 'workspaceFiles.title': 'Agent 工作区文件', 'workspaceFiles.readOnly': '只读', 'workspaceFiles.root': '工作区', 'workspaceFiles.startProject': '启动项目后即可查看该 Agent 的工作区。', 'workspaceFiles.empty': '当前目录为空。', 'workspaceFiles.selectFile': '选择文件后可在这里预览。', 'workspaceFiles.binary': '二进制文件暂不支持预览。', 'workspaceFiles.tooLarge': '文件超过 512 KB 的预览上限。',
  'git.title': 'Git 交付状态', 'git.refresh': '刷新 Git 状态', 'git.startProject': '启动项目后可查看各 Agent 分支并修改 Git 设置。', 'git.remoteEnabled': '已启用远程发布', 'git.remoteDisabled': '未启用远程发布', 'git.localOnly': '仅使用本地 Git', 'git.identityValid': '本地身份有效', 'git.identityMissing': '本地身份不完整', 'git.merged': '已合并', 'git.pushed': '已推送', 'git.dirty': '有未提交修改', 'git.clean': '工作区干净', 'git.notMerged': '未合并', 'git.configure': '本地与远程设置', 'git.remoteName': '远程名称（可选）', 'git.remoteUrl': '远程地址（可选）', 'git.userName': 'Git 用户名', 'git.userEmail': 'Git 用户邮箱', 'git.enablePush': '启用远程发布', 'git.adminOnly': '仅 Admin 可显式推送已合并的 release；凭据由 SSH Agent 或 Git credential helper 管理。', 'git.save': '保存 Git 设置', 'git.saving': '保存中…',
  'docker.title': 'Docker 运行环境', 'docker.subtitle': '查看并安全管理 OAT Agent 容器。', 'docker.refresh': '刷新', 'docker.engine': 'Docker Engine', 'docker.available': '可用', 'docker.unavailable': '不可用', 'docker.runtime': '项目运行模式', 'docker.isolated': 'Docker 隔离', 'docker.localProcess': '本地进程隔离', 'docker.locked': '已永久锁定为 Docker 隔离', 'docker.canMigrate': '可以单向迁移到 Docker', 'docker.containers': '受管容器', 'docker.running': '运行中', 'docker.configuration': 'Docker 配置', 'docker.migrate': '将运行环境迁移到 Docker', 'docker.noDowngrade': '可以修改镜像、网络和资源限制，但不能降级回本地进程。', 'docker.migrateHint': '迁移会重启项目，而且不可逆。', 'docker.image': '镜像', 'docker.network': '网络', 'docker.extraArgs': '资源与安全参数', 'docker.safeArgs': '允许 CPU、内存、PID、ulimit、tmpfs 限制，以及只读、cap-drop=ALL 和 no-new-privileges。', 'docker.saving': '保存中…', 'docker.saveRestart': '保存并重启项目', 'docker.migrateRestart': '迁移并重启项目', 'docker.managedContainers': 'Agent 容器', 'docker.status': '状态', 'docker.logs': '日志', 'docker.restartAgent': '重启空闲 Agent', 'docker.restarting': '重启中…', 'docker.noContainers': '当前没有正在运行的受管 Agent 容器。', 'docker.migrateToManage': '将项目迁移到 Docker 后即可管理 Agent 容器。', 'docker.close': '关闭', 'docker.noLogs': '没有日志输出。', 'docker.migrationConfirm': '确定将项目迁移到 Docker 隔离吗？项目会重启，而且迁移不可逆。',
  'docker.remove': '清理孤儿容器', 'docker.removeConfirm': '确定清理这个已停止或孤立的 OAT 容器吗？',
  'time.second': '秒', 'time.minute': '分钟', 'time.hour': '小时', 'time.day': '天',
  'management.eyebrow': '声明式控制', 'management.title': '配置与模型', 'management.refresh': '刷新', 'management.teamConfig': '项目团队配置', 'management.teamConfigHint': '配置页会跟随左侧当前选中的 Agent。项目共享设置显示在上方，下方只显示该 Agent 所属团队的配置。', 'management.project': '项目', 'management.team': '团队', 'management.projectScope': '项目设置', 'management.adminScope': '管理员设置', 'management.administrator': '管理员', 'management.saved': '已保存', 'management.unsavedDraft': '未保存草稿', 'management.chooseModel': '选择模型', 'management.inheritDefault': '继承默认模型', 'management.addTeam': '添加独立团队', 'management.reloadFields': '从 JSON 重新加载结构化字段', 'management.discardDraft': '放弃本地草稿', 'management.modelsProviders': '模型与 Provider', 'management.modelsProvidersHint': '项目别名会被下方所有模型选择器使用。Provider 密钥、地址和仅测试凭据仍保存在 team.json 中。', 'management.removeProvider': '移除 Provider', 'management.providerKey': 'Provider 键', 'management.protocol': '协议', 'management.compatible': '兼容', 'management.baseUrl': '基础 URL', 'management.apiKey': 'API 密钥', 'management.noProviders': '尚未配置项目 Provider。', 'management.addProvider': '添加 Provider', 'management.syncModels': '获取并同步所有模型', 'management.modelAliases': '模型别名', 'management.addAlias': '添加别名', 'management.alias': '别名', 'management.providerModelId': 'Provider 模型 ID', 'management.remove': '移除', 'management.noAliases': '尚未配置模型别名。',
  'management.addSkill': '添加技能', 'management.skillSource': '技能来源', 'management.skillNames': '技能名称', 'management.skillHint': '以逗号分隔多个技能名称。', 'management.noSkills': '尚未配置技能。', 'management.teamIdentifier': '团队标识', 'management.branchPrefix': '分支前缀', 'management.leaderName': '组长名称', 'management.leaderModel': '组长模型', 'management.leaderResponsibility': '组长职责', 'management.leaderPrompt': '组长提示词', 'management.leaderRepos': '允许的仓库 / 路径', 'management.reposHint': '以逗号分隔仓库名称或路径。', 'management.leaderSkills': '组长技能', 'management.workerCount': 'Worker 数量', 'management.workerModel': 'Worker 模型', 'management.workerPrompt': 'Worker 提示词', 'management.skillSync': '技能同步方式', 'management.inheritInject': '创建时继承并注入', 'management.manual': '手动', 'management.workerSkills': 'Worker 技能', 'management.noSelectedTeam': '未找到与当前选中 Agent 对应的团队。',
  'management.projectRuntimeWorkspace': '共享项目、运行时与工作区', 'management.projectRuntimeWorkspaceHint': '这些设置会被当前项目中的所有 Agent 共用。', 'management.projectName': '项目名称', 'management.repositoryPath': '仓库路径', 'management.baseBranch': '基础分支', 'management.defaultModel': '默认模型', 'management.runtimeMode': '运行模式', 'management.localProcess': '本地进程', 'management.dockerSandbox': 'Docker 沙箱', 'management.dockerLocked': '该项目已永久要求使用 Docker 隔离。', 'management.dockerMigrationHint': '迁移至 Docker 为单向操作，并会重启项目。', 'management.stateDirectory': '状态目录', 'management.dockerImage': 'Docker 镜像', 'management.dockerNetwork': 'Docker 网络', 'management.dockerArgs': 'Docker 额外参数', 'management.dockerArgsHint': '以逗号分隔多个参数。', 'management.workspaceProvider': '工作区提供方式', 'management.worktree': 'Git 工作树', 'management.sharedClone': '共享克隆', 'management.fullClone': '完整克隆', 'management.workspaceRoot': '工作区根目录', 'management.gitRemote': 'Git 远程名称', 'management.gitRemoteUrl': 'Git 远程地址', 'management.gitUserName': 'Git 用户名', 'management.gitUserEmail': 'Git 用户邮箱', 'management.adminPush': '允许 Admin 推送远程分支', 'management.gitLfs': 'Git LFS', 'management.pull': '拉取', 'management.skip': '跳过', 'management.allowPullDenyChange': '允许拉取，禁止修改', 'management.sparseCheckout': '稀疏检出', 'management.adminName': '管理员名称', 'management.adminModel': '管理员模型', 'management.adminDescription': '管理员职责', 'management.adminPrompt': '管理员提示词', 'management.save': '保存项目配置', 'management.restartProject': '重启当前项目',
  'management.globalModelCatalog': '全局模型目录', 'management.globalModelCatalogHint': '模型可用范围只在全局设置中管理；项目配置仅保存选择结果，不再维护 Provider 或注册表条目。', 'management.savedMessage': '项目配置已保存。',
  'settings.eyebrow': '全局控制', 'settings.subtitle': '管理此 Desktop 的共享偏好与模型注册表。', 'settings.retention': '日志保留', 'settings.retentionHint': '保留 1 至 365 天的可观测性日志。', 'settings.retentionDays': '日志保留天数', 'settings.saveRetention': '保存保留设置', 'settings.registry': '全局模型注册表', 'settings.registryHint': '共享模型可供每个项目使用；删除条目不会修改现有 team.json 声明。', 'settings.provider': 'Provider', 'settings.key': '密钥', 'settings.actions': '操作', 'settings.configured': '已配置', 'settings.noProviders': '尚未配置 Provider。', 'settings.noModels': '尚未注册模型。', 'settings.modelAlias': '模型别名', 'settings.providerModel': 'Provider 模型', 'settings.copy': '复制', 'settings.clearRegistry': '清空所有 Provider 和模型', 'settings.advanced': '高级全局配置', 'settings.advancedHint': '仅在需要编辑上方未覆盖的设置时使用。', 'settings.saveGlobal': '保存全局配置',
  'settings.providerName': 'Provider 名称', 'settings.testApiKey': '连接测试 API 密钥', 'settings.connectProvider': '测试连接并同步模型',
  'startup.title': '正在初始化 Open Agent Team', 'startup.subtitle': '正在准备本地工作区。', 'startup.services': '正在初始化 Desktop 服务…', 'startup.node': 'Node.js 环境', 'startup.oat': 'OAT 工具', 'startup.docker': 'Docker 环境', 'startup.desktopServices': 'Desktop 服务', 'startup.pending': '等待检查', 'startup.checking': '检查中…', 'startup.checkingNode': '正在检查 Node.js 兼容性…', 'startup.checkingOat': '正在检查 OAT 命令行工具…', 'startup.checkingDocker': '正在检查本地 Docker 环境…', 'startup.ready': '已就绪', 'startup.installing': '正在安装本地运行环境…', 'startup.installingNode': '正在安装受管 Node.js 运行环境…', 'startup.installingOat': '正在安装 OAT 工具…', 'startup.nodeUnavailable': '没有可用的兼容 Node.js 运行环境。', 'startup.oatUnavailable': 'OAT 工具不可用。', 'startup.dockerNotInstalled': '未安装 · 可稍后在 Docker 管理中配置', 'startup.dockerStopped': '已安装 · Docker Engine 未运行', 'startup.dockerPermission': '已安装 · daemon 访问权限需要处理', 'startup.dockerDeferred': '暂时无法检查 · 可稍后在 Docker 管理中配置', 'startup.retry': '重试', 'startup.failed': '启动检查失败',
};
const fr: Dictionary = { ...en, 'app.ready': 'OAT prêt', 'app.setup': 'Configurer OAT', 'app.settings': 'Paramètres', 'app.theme': 'Thème', 'app.language': 'Langue', 'theme.system': 'Système', 'theme.light': 'Clair', 'theme.dark': 'Sombre', 'settings.title': 'Paramètres', 'settings.general': 'Préférences de l’application', 'settings.globalConfig': 'Configuration globale', 'settings.models': 'Configuration des modèles', 'settings.save': 'Enregistrer', 'settings.saved': 'Enregistré', 'settings.failed': 'Échec de l’enregistrement', 'workspace.back': 'Espace de travail', 'workspace.operate': 'Exécuter', 'workspace.insights': 'Analyses', 'workspace.configure': 'Configurer', 'workspace.tasks': 'File de tâches', 'workspace.monitor': 'Activité en direct', 'workspace.usage': 'Utilisation', 'workspace.achievements': 'Résultats', 'workspace.config': 'Configuration d’équipe', 'workspace.resources': 'Ressources Agent', 'workspace.plugins': 'Extensions', 'workspace.channels': 'Canaux', 'resource.history': 'Historique des conversations', 'resource.projects': 'PROJETS', 'resource.thinking': 'Réflexion…', 'chat.you': 'Vous', 'chat.startAdmin': 'Commencer avec l’administrateur', 'chat.report': 'Flux de rapports Agent', 'chat.addContext': 'Ajouter du contexte', 'chat.approval': 'Demander une approbation', 'chat.voice': 'Entrée vocale', 'chat.send': 'Envoyer', 'queue.queued': 'En attente', 'queue.drag': 'Glisser pour réordonner', 'queue.delete': 'Supprimer la tâche', 'status.available': 'Disponible', 'status.busy': 'Occupé', 'status.offline': 'Hors ligne', 'status.running': 'En cours', 'status.completed': 'Terminé', 'status.failed': 'Échec', 'agent.none': 'Aucun Agent sélectionné', 'agent.inbox': 'Boîte de tâches', 'agent.reportOnly': 'Rapports uniquement', 'agent.taskProgress': 'Progression', 'agent.workQueue': 'File de travail', 'agent.allowed': 'Informations autorisées', 'agent.policy': 'Politique d’interaction', 'agent.project': 'Projet', 'agent.model': 'Modèle', 'agent.workspace': 'Espace de travail', 'agent.repositories': 'Dépôts', 'agent.skills': 'Compétences', 'agent.access': 'Accès', 'loading': 'Chargement des données locales…' };
const ja: Dictionary = { ...en, 'app.ready': 'OAT 準備完了', 'app.setup': 'OAT を設定', 'app.settings': '設定', 'app.theme': 'テーマ', 'app.language': '言語', 'theme.system': 'システム', 'theme.light': 'ライト', 'theme.dark': 'ダーク', 'settings.title': '設定', 'settings.general': 'アプリの設定', 'settings.globalConfig': 'グローバル設定', 'settings.models': 'グローバルモデル設定', 'settings.save': '保存', 'settings.saved': '保存しました', 'settings.failed': '保存に失敗しました', 'workspace.back': 'ワークスペース', 'workspace.operate': '操作', 'workspace.insights': '分析', 'workspace.configure': '構成', 'workspace.tasks': 'タスクキュー', 'workspace.monitor': 'ライブアクティビティ', 'workspace.usage': '使用量', 'workspace.achievements': '成果', 'workspace.config': 'チーム設定', 'workspace.resources': 'Agent リソース', 'workspace.plugins': 'プラグイン', 'workspace.channels': 'チャネル', 'resource.history': '会話履歴', 'resource.projects': 'プロジェクト', 'resource.thinking': '思考中…', 'chat.you': 'あなた', 'chat.startAdmin': '管理者との会話を開始', 'chat.report': 'Agent レポート', 'chat.addContext': 'コンテキストを追加', 'chat.approval': '承認を依頼', 'chat.voice': '音声入力', 'chat.send': '送信', 'queue.queued': '待機中', 'queue.drag': 'ドラッグして並べ替え', 'queue.delete': '待機中のタスクを削除', 'status.available': '利用可能', 'status.busy': '処理中', 'status.offline': 'オフライン', 'status.running': '実行中', 'status.completed': '完了', 'status.failed': '失敗', 'agent.none': 'Agent が選択されていません', 'agent.inbox': 'タスク受信箱', 'agent.reportOnly': 'レポートのみ', 'agent.taskProgress': 'タスクの進捗', 'agent.workQueue': '作業キュー', 'agent.allowed': '許可された情報', 'agent.policy': '操作ポリシー', 'agent.project': 'プロジェクト', 'agent.model': 'モデル', 'agent.workspace': 'ワークスペース', 'agent.repositories': 'リポジトリ', 'agent.skills': 'スキル', 'agent.access': 'アクセス', 'loading': 'ローカル制御データを読み込み中…' };
Object.assign(en, { 'memory.open': 'View Agent memory', 'memory.title': 'Agent memory', 'memory.subtitle': 'Inspect working, long-term, and deep memory with traceable evidence.', 'memory.l1': 'Working memory', 'memory.l2': 'Long-term memory', 'memory.l3': 'Deep memory', 'memory.pending': 'Pending observations', 'memory.agent': 'Memory owner', 'memory.lastActivity': 'Last activity', 'memory.lastDream': 'Last dream', 'memory.dreamResult': 'Consolidation result', 'memory.refresh': 'Refresh memory', 'memory.dream': 'Consolidate now', 'memory.dreaming': 'Consolidating…', 'memory.busy': 'Memory consolidation waits until all project tasks are idle.', 'memory.startProject': 'Start the project to inspect persistent Agent memory.', 'memory.empty': 'No memory has been recorded at this level.', 'memory.promote': 'Promote to L3', 'memory.forget': 'Forget', 'memory.forgetConfirm': 'Forget this memory? It will no longer be retrieved or injected.', 'memory.confidence': 'Confidence', 'memory.salience': 'Salience', 'memory.evidence': 'Evidence', 'memory.sources': 'Sources' });
Object.assign(zh, { 'memory.open': '查看 Agent 记忆', 'memory.title': 'Agent 记忆', 'memory.subtitle': '查看可追溯来源的短期、长期和深层记忆。', 'memory.l1': '短期记忆', 'memory.l2': '长期记忆', 'memory.l3': '深层记忆', 'memory.pending': '待沉淀观察', 'memory.agent': '记忆归属 Agent', 'memory.lastActivity': '最近活动', 'memory.lastDream': '最近做梦', 'memory.dreamResult': '沉淀结果', 'memory.refresh': '刷新记忆', 'memory.dream': '立即沉淀', 'memory.dreaming': '正在沉淀…', 'memory.busy': '项目存在活动任务，记忆沉淀将在全部任务空闲后进行。', 'memory.startProject': '启动项目后可查看持久化的 Agent 记忆。', 'memory.empty': '该层级尚未形成记忆。', 'memory.promote': '晋升为 L3', 'memory.forget': '遗忘', 'memory.forgetConfirm': '遗忘这条记忆吗？之后将不再检索或注入。', 'memory.confidence': '置信度', 'memory.salience': '重要度', 'memory.evidence': '证据', 'memory.sources': '来源' });
Object.assign(fr, { 'memory.open': 'Voir la mémoire Agent', 'memory.title': 'Mémoire Agent', 'memory.subtitle': 'Inspecter la mémoire de travail, à long terme et profonde avec ses preuves.', 'memory.l1': 'Mémoire de travail', 'memory.l2': 'Mémoire à long terme', 'memory.l3': 'Mémoire profonde', 'memory.pending': 'Observations en attente', 'memory.agent': 'Agent propriétaire', 'memory.lastActivity': 'Dernière activité', 'memory.lastDream': 'Dernière consolidation', 'memory.dreamResult': 'Résultat', 'memory.refresh': 'Actualiser', 'memory.dream': 'Consolider', 'memory.dreaming': 'Consolidation…', 'memory.busy': 'La consolidation attend que toutes les tâches soient inactives.', 'memory.startProject': 'Démarrez le projet pour voir la mémoire persistante.', 'memory.empty': 'Aucune mémoire à ce niveau.', 'memory.promote': 'Promouvoir en L3', 'memory.forget': 'Oublier', 'memory.forgetConfirm': 'Oublier cette mémoire ?', 'memory.confidence': 'Confiance', 'memory.salience': 'Importance', 'memory.evidence': 'Preuves', 'memory.sources': 'Sources' });
Object.assign(ja, { 'memory.open': 'Agent メモリを表示', 'memory.title': 'Agent メモリ', 'memory.subtitle': '根拠を追跡できる作業・長期・深層メモリを確認します。', 'memory.l1': '作業メモリ', 'memory.l2': '長期メモリ', 'memory.l3': '深層メモリ', 'memory.pending': '未整理の観察', 'memory.agent': 'メモリ所有 Agent', 'memory.lastActivity': '最終活動', 'memory.lastDream': '最終整理', 'memory.dreamResult': '整理結果', 'memory.refresh': '更新', 'memory.dream': '今すぐ整理', 'memory.dreaming': '整理中…', 'memory.busy': 'すべてのタスクが待機状態になるまで整理を待ちます。', 'memory.startProject': 'プロジェクトを開始すると永続メモリを確認できます。', 'memory.empty': 'このレベルのメモリはありません。', 'memory.promote': 'L3 に昇格', 'memory.forget': '忘却', 'memory.forgetConfirm': 'このメモリを忘却しますか？', 'memory.confidence': '信頼度', 'memory.salience': '重要度', 'memory.evidence': '根拠', 'memory.sources': '出典' });
Object.assign(en, { 'logs.open': 'Log maintenance', 'logs.title': 'Log maintenance', 'logs.subtitle': 'Review and clean disposable runtime diagnostics for the current project.', 'logs.scan': 'Scan Agent logs', 'logs.scanning': 'Scanning…', 'logs.boundaryTitle': 'Logs and memory are separate', 'logs.boundaryText': 'This page manages only runtime diagnostic files. Cleanup never changes Agent knowledge or task records.', 'logs.scopeRuntime': 'Runtime logs: disposable diagnostic .jsonl files', 'logs.scopeMemory': 'Short-term and persistent memory: preserved', 'logs.scopeTask': 'Task snapshots and delivery reports: preserved', 'logs.retentionTitle': 'Automatic cleanup', 'logs.retentionText': 'Logs older than this retention period are removed automatically when OAT starts; you can also clean them now.', 'logs.retentionDays': 'Keep logs for days', 'logs.retentionInvalid': 'Retention must be a whole number from 1 to 365.', 'logs.save': 'Save retention', 'logs.saving': 'Saving…', 'logs.startProject': 'Start the current project before scanning its Agent logs.', 'logs.readyToScan': 'Ready to scan', 'logs.readyToScanText': 'Scan to see each Agent workspace’s log files and storage use.', 'logs.agentFolders': 'Agent workspaces', 'logs.files': 'Log files', 'logs.totalSize': 'Total size', 'logs.agentBreakdown': 'Agent log breakdown', 'logs.agentBreakdownText': 'Largest log sets appear first.', 'logs.cleanupNow': 'Clean expired logs', 'logs.cleaning': 'Cleaning…', 'logs.cleanupConfirm': 'Delete runtime log files older than {days} days? Memory, task snapshots, and delivery reports will not be affected.', 'logs.cleaned': 'Removed {count} expired log file(s).', 'logs.agent': 'Agent', 'logs.latest': 'Latest write', 'logs.none': 'No Agent runtime log files were found.' });
Object.assign(zh, { 'logs.open': '日志维护', 'logs.title': '日志清理', 'logs.subtitle': '扫描并清理当前项目中可安全删除的 Agent 运行日志。', 'logs.scan': '扫描团队日志', 'logs.scanning': '扫描中…', 'logs.boundaryTitle': '日志与记忆相互独立', 'logs.boundaryText': '此页面仅管理运行诊断日志。清理不会改变 Agent 的知识、短期记忆或任务记录。', 'logs.scopeRuntime': '运行日志：可清理的诊断 .jsonl 文件', 'logs.scopeMemory': '短期记忆及持久记忆：不会删除', 'logs.scopeTask': '任务快照与交付汇报：不会删除', 'logs.retentionTitle': '自动清理', 'logs.retentionText': 'OAT 启动时会自动删除超过保留期的日志；也可以在下方立即执行清理。', 'logs.retentionDays': '日志保留天数', 'logs.retentionInvalid': '保留天数必须是 1 到 365 之间的整数。', 'logs.save': '保存保留期', 'logs.saving': '保存中…', 'logs.startProject': '请先启动当前项目，再扫描团队 Agent 日志。', 'logs.readyToScan': '准备就绪', 'logs.readyToScanText': '点击“扫描团队日志”查看每个 Agent 工作区的日志文件与占用空间。', 'logs.agentFolders': 'Agent 工作区', 'logs.files': '日志文件', 'logs.totalSize': '总占用', 'logs.agentBreakdown': '按 Agent 查看日志', 'logs.agentBreakdownText': '按占用空间从大到小排列。', 'logs.cleanupNow': '清理过期日志', 'logs.cleaning': '清理中…', 'logs.cleanupConfirm': '删除超过 {days} 天的运行日志吗？短期记忆、任务快照和交付汇报不会受到影响。', 'logs.cleaned': '已清理 {count} 个过期日志文件。', 'logs.agent': 'Agent', 'logs.latest': '最近写入', 'logs.none': '未发现 Agent 运行日志文件。' });
Object.assign(fr, { 'resource.agent': 'Responsable des ressources Agent' });
Object.assign(ja, { 'resource.agent': 'エージェントリソース管理者' });
Object.assign(fr, { 'git.title': 'Livraison Git', 'git.refresh': 'Actualiser l’état Git', 'git.startProject': 'Démarrez le projet pour inspecter les branches Agent et modifier Git.', 'git.remoteEnabled': 'publication activée', 'git.remoteDisabled': 'publication désactivée', 'git.localOnly': 'Git local uniquement', 'git.identityValid': 'Identité locale valide', 'git.identityMissing': 'Identité locale incomplète', 'git.merged': 'fusionné', 'git.pushed': 'poussé', 'git.dirty': 'non validé', 'git.clean': 'propre', 'git.notMerged': 'non fusionné', 'git.configure': 'Paramètres locaux et distants', 'git.remoteName': 'Nom distant (facultatif)', 'git.remoteUrl': 'URL distante (facultative)', 'git.userName': 'Nom utilisateur Git', 'git.userEmail': 'E-mail utilisateur Git', 'git.enablePush': 'Activer la publication distante', 'git.adminOnly': 'Seul Admin peut pousser explicitement une version fusionnée. Les identifiants restent dans SSH Agent ou le gestionnaire Git.', 'git.save': 'Enregistrer Git', 'git.saving': 'Enregistrement…' });
Object.assign(ja, { 'git.title': 'Git 配信状態', 'git.refresh': 'Git 状態を更新', 'git.startProject': 'プロジェクトを開始すると Agent のブランチ確認と Git 設定の変更ができます。', 'git.remoteEnabled': 'リモート公開有効', 'git.remoteDisabled': 'リモート公開無効', 'git.localOnly': 'ローカル Git のみ', 'git.identityValid': 'ローカル ID は有効', 'git.identityMissing': 'ローカル ID が不完全', 'git.merged': 'マージ済み', 'git.pushed': 'push 済み', 'git.dirty': '未コミット', 'git.clean': 'クリーン', 'git.notMerged': '未マージ', 'git.configure': 'ローカルとリモートの設定', 'git.remoteName': 'リモート名（任意）', 'git.remoteUrl': 'リモート URL（任意）', 'git.userName': 'Git ユーザー名', 'git.userEmail': 'Git ユーザーメール', 'git.enablePush': 'リモート公開を有効化', 'git.adminOnly': 'マージ済みリリースを明示的に push できるのは Admin のみです。認証情報は SSH Agent または Git credential helper で管理します。', 'git.save': 'Git 設定を保存', 'git.saving': '保存中…' });
Object.assign(fr, { 'workspace.docker': 'Runtime Docker', 'docker.title': 'Runtime Docker', 'docker.subtitle': 'Inspecter et gérer en sécurité les conteneurs Agent OAT.', 'docker.refresh': 'Actualiser', 'docker.engine': 'Moteur Docker', 'docker.available': 'Disponible', 'docker.unavailable': 'Indisponible', 'docker.runtime': 'Runtime du projet', 'docker.isolated': 'Isolation Docker', 'docker.localProcess': 'Isolation par processus local', 'docker.locked': 'Docker est définitivement requis', 'docker.canMigrate': 'Migration unidirectionnelle disponible', 'docker.containers': 'Conteneurs gérés', 'docker.running': 'actifs', 'docker.configuration': 'Configuration Docker', 'docker.migrate': 'Migrer vers Docker', 'docker.noDowngrade': 'L’image, le réseau et les limites restent modifiables, sans retour aux processus locaux.', 'docker.migrateHint': 'La migration redémarre le projet et est irréversible.', 'docker.image': 'Image', 'docker.network': 'Réseau', 'docker.extraArgs': 'Limites et durcissement', 'docker.safeArgs': 'Seules les limites de ressources et les options de durcissement sûres sont autorisées.', 'docker.saving': 'Enregistrement…', 'docker.saveRestart': 'Enregistrer et redémarrer', 'docker.migrateRestart': 'Migrer et redémarrer', 'docker.managedContainers': 'Conteneurs Agent', 'docker.status': 'État', 'docker.logs': 'Journaux', 'docker.restartAgent': 'Redémarrer l’Agent inactif', 'docker.restarting': 'Redémarrage…', 'docker.noContainers': 'Aucun conteneur Agent géré en cours.', 'docker.migrateToManage': 'Migrez vers Docker pour gérer les conteneurs Agent.', 'docker.close': 'Fermer', 'docker.noLogs': 'Aucun journal.', 'docker.migrationConfirm': 'Migrer ce projet vers Docker ? Le redémarrage est irréversible.' });
Object.assign(ja, { 'workspace.docker': 'Docker ランタイム', 'docker.title': 'Docker ランタイム', 'docker.subtitle': 'OAT Agent コンテナを安全に確認・管理します。', 'docker.refresh': '更新', 'docker.engine': 'Docker Engine', 'docker.available': '利用可能', 'docker.unavailable': '利用不可', 'docker.runtime': 'プロジェクトランタイム', 'docker.isolated': 'Docker 分離', 'docker.localProcess': 'ローカルプロセス分離', 'docker.locked': 'Docker 分離が恒久的に必要です', 'docker.canMigrate': 'Docker への一方向移行が可能です', 'docker.containers': '管理対象コンテナ', 'docker.running': '実行中', 'docker.configuration': 'Docker 設定', 'docker.migrate': 'Docker へ移行', 'docker.noDowngrade': 'イメージ、ネットワーク、制限は変更できますがローカルプロセスへ戻せません。', 'docker.migrateHint': '移行はプロジェクトを再起動し、元に戻せません。', 'docker.image': 'イメージ', 'docker.network': 'ネットワーク', 'docker.extraArgs': 'リソース・強化設定', 'docker.safeArgs': '安全なリソース制限と強化オプションのみ使用できます。', 'docker.saving': '保存中…', 'docker.saveRestart': '保存して再起動', 'docker.migrateRestart': '移行して再起動', 'docker.managedContainers': 'Agent コンテナ', 'docker.status': '状態', 'docker.logs': 'ログ', 'docker.restartAgent': '待機中 Agent を再起動', 'docker.restarting': '再起動中…', 'docker.noContainers': '実行中の管理対象 Agent コンテナはありません。', 'docker.migrateToManage': 'Docker へ移行すると Agent コンテナを管理できます。', 'docker.close': '閉じる', 'docker.noLogs': 'ログはありません。', 'docker.migrationConfirm': 'Docker 分離へ移行しますか？再起動後は元に戻せません。' });
Object.assign(fr, { 'docker.remove': 'Supprimer l’orphelin', 'docker.removeConfirm': 'Supprimer ce conteneur OAT arrêté ou orphelin ?' });
Object.assign(ja, { 'docker.remove': '孤立コンテナを削除', 'docker.removeConfirm': '停止済みまたは孤立した OAT コンテナを削除しますか？' });
Object.assign(en, { 'docker.notInstalled': 'Docker is not installed', 'docker.daemonStopped': 'Docker Engine is stopped', 'docker.daemonStoppedHint': 'Docker is installed locally. Start its engine before migrating or running Agent containers.', 'docker.install': 'Install Docker', 'docker.installing': 'Installing Docker…', 'docker.installConfirm': 'Install Docker on this computer now? The installer may download software, request administrator approval, and requires acceptance of Docker’s terms and applicable licensing.', 'docker.installNotice': 'Docker is required for container isolation. Installation starts only after your confirmation and may request system authorization. Review Docker’s terms and licensing before continuing.', 'docker.installGuide': 'Official installation guide', 'docker.start': 'Start Docker', 'docker.starting': 'Starting Docker…' });
Object.assign(zh, { 'docker.notInstalled': '本地未安装 Docker', 'docker.daemonStopped': 'Docker Engine 未启动', 'docker.daemonStoppedHint': '已检测到本地 Docker。迁移或运行 Agent 容器前，请先启动 Docker Engine。', 'docker.install': '安装 Docker', 'docker.installing': '正在安装 Docker…', 'docker.installConfirm': '现在在这台电脑上安装 Docker 吗？安装程序可能会下载软件、请求管理员授权，并要求你接受 Docker 的条款及适用许可。', 'docker.installNotice': '容器隔离需要 Docker。只有在你确认后才会开始安装，期间可能请求系统授权；继续前请查看 Docker 的条款与许可。', 'docker.installGuide': '官方安装指南', 'docker.start': '启动 Docker', 'docker.starting': '正在启动 Docker…' });
Object.assign(fr, { 'docker.notInstalled': 'Docker n’est pas installé', 'docker.daemonStopped': 'Docker Engine est arrêté', 'docker.daemonStoppedHint': 'Docker est installé localement. Démarrez son moteur avant toute migration ou exécution de conteneurs Agent.', 'docker.install': 'Installer Docker', 'docker.installing': 'Installation de Docker…', 'docker.installConfirm': 'Installer Docker sur cet ordinateur maintenant ? Le programme peut télécharger des logiciels, demander une autorisation administrateur et exige l’acceptation des conditions et licences Docker.', 'docker.installNotice': 'Docker est requis pour l’isolation par conteneurs. L’installation ne démarre qu’après votre confirmation et peut demander une autorisation système.', 'docker.installGuide': 'Guide d’installation officiel', 'docker.start': 'Démarrer Docker', 'docker.starting': 'Démarrage de Docker…' });
Object.assign(ja, { 'docker.notInstalled': 'Docker がインストールされていません', 'docker.daemonStopped': 'Docker Engine が停止しています', 'docker.daemonStoppedHint': 'Docker はローカルにインストール済みです。移行や Agent コンテナの実行前に Engine を起動してください。', 'docker.install': 'Docker をインストール', 'docker.installing': 'Docker をインストール中…', 'docker.installConfirm': 'このコンピューターに Docker をインストールしますか？ソフトウェアのダウンロードや管理者承認が必要になる場合があり、Docker の規約と適用ライセンスへの同意が必要です。', 'docker.installNotice': 'コンテナ分離には Docker が必要です。確認後にのみインストールを開始し、システム承認を求める場合があります。', 'docker.installGuide': '公式インストールガイド', 'docker.start': 'Docker を起動', 'docker.starting': 'Docker を起動中…' });
Object.assign(en, { 'docker.permissionDenied': 'Docker Engine access denied', 'docker.permissionDeniedHint': 'Docker is installed, but this user cannot access its daemon. Restart Docker Desktop or apply the required Docker socket/group permission, then try again.' });
Object.assign(zh, { 'docker.permissionDenied': '无权访问 Docker Engine', 'docker.permissionDeniedHint': 'Docker 已安装，但当前用户无法访问 daemon。请重启 Docker Desktop，或配置所需的 Docker socket/用户组权限后重试。' });
Object.assign(fr, { 'docker.permissionDenied': 'Accès à Docker Engine refusé', 'docker.permissionDeniedHint': 'Docker est installé, mais cet utilisateur ne peut pas accéder au daemon. Redémarrez Docker Desktop ou corrigez les permissions du socket/groupe Docker.' });
Object.assign(ja, { 'docker.permissionDenied': 'Docker Engine へのアクセスが拒否されました', 'docker.permissionDeniedHint': 'Docker はインストール済みですが、このユーザーは daemon にアクセスできません。Docker Desktop を再起動するか、Docker socket／グループ権限を設定してください。' });
Object.assign(fr, { 'startup.services': 'Initialisation des services Desktop…', 'startup.oat': 'Outil OAT', 'startup.docker': 'Environnement Docker', 'startup.desktopServices': 'Services Desktop', 'startup.pending': 'En attente de vérification', 'startup.checkingNode': 'Vérification de la compatibilité Node.js…', 'startup.checkingOat': 'Vérification de l’outil OAT…', 'startup.checkingDocker': 'Vérification de l’environnement Docker local…', 'startup.installingNode': 'Installation d’un runtime Node.js géré…', 'startup.installingOat': 'Installation de l’outil OAT…', 'startup.nodeUnavailable': 'Aucun runtime Node.js compatible n’est disponible.', 'startup.oatUnavailable': 'L’outil OAT n’est pas disponible.', 'startup.dockerNotInstalled': 'Non installé · configurable plus tard dans la gestion Docker', 'startup.dockerStopped': 'Installé · Docker Engine n’est pas démarré', 'startup.dockerPermission': 'Installé · l’accès au daemon nécessite une intervention', 'startup.dockerDeferred': 'Vérification indisponible · configurable plus tard' });
Object.assign(ja, { 'startup.services': 'Desktop サービスを初期化中…', 'startup.oat': 'OAT ツール', 'startup.docker': 'Docker 環境', 'startup.desktopServices': 'Desktop サービス', 'startup.pending': '確認待ち', 'startup.checkingNode': 'Node.js の互換性を確認中…', 'startup.checkingOat': 'OAT コマンドラインツールを確認中…', 'startup.checkingDocker': 'ローカル Docker 環境を確認中…', 'startup.installingNode': '管理対象 Node.js ランタイムをインストール中…', 'startup.installingOat': 'OAT ツールをインストール中…', 'startup.nodeUnavailable': '互換性のある Node.js ランタイムを利用できません。', 'startup.oatUnavailable': 'OAT ツールを利用できません。', 'startup.dockerNotInstalled': '未インストール · Docker 管理で後から設定できます', 'startup.dockerStopped': 'インストール済み · Docker Engine は停止中です', 'startup.dockerPermission': 'インストール済み · daemon アクセス権限の確認が必要です', 'startup.dockerDeferred': '確認できません · Docker 管理で後から設定できます' });
Object.assign(en, { 'taskPanel.finished': 'Finished' });
Object.assign(zh, { 'taskPanel.finished': '已结束' });
Object.assign(fr, { 'taskPanel.finished': 'Terminées' });
Object.assign(ja, { 'taskPanel.finished': '終了' });
Object.assign(en, { 'chat.workerReport': 'Worker completion report', 'chat.leaderReport': 'Leader completion report', 'chat.workerReportDefault': 'Implementation is complete and has been submitted for Leader review.', 'chat.leaderReportDefault': 'Worker deliveries were reviewed and integrated; the release proposal is ready for Admin approval.', 'chat.reviewRequest': 'Review request', 'chat.releaseProposal': 'Release proposal', 'chat.deliveryBranch': 'Delivery branch', 'chat.changedFiles': 'Changed files', 'chat.testResults': 'Test results', 'chat.artifacts': 'Delivery artifacts' });
Object.assign(zh, { 'chat.workerReport': 'Worker 完成汇报', 'chat.leaderReport': 'Leader 完成汇报', 'chat.workerReportDefault': '实现已完成，并已提交给 Leader 审查。', 'chat.leaderReportDefault': 'Worker 交付已完成审查与集成，发布提案已提交给 Admin 审批。', 'chat.reviewRequest': '审查请求', 'chat.releaseProposal': '发布提案', 'chat.deliveryBranch': '交付分支', 'chat.changedFiles': '变更文件', 'chat.testResults': '测试结果', 'chat.artifacts': '交付产物' });
Object.assign(fr, { 'chat.workerReport': 'Rapport final du Worker', 'chat.leaderReport': 'Rapport final du Leader', 'chat.reviewRequest': 'Demande de revue', 'chat.releaseProposal': 'Proposition de livraison', 'chat.deliveryBranch': 'Branche de livraison', 'chat.changedFiles': 'Fichiers modifiés', 'chat.testResults': 'Résultats des tests' });
Object.assign(ja, { 'chat.workerReport': 'Worker 完了レポート', 'chat.leaderReport': 'Leader 完了レポート', 'chat.reviewRequest': 'レビュー依頼', 'chat.releaseProposal': 'リリース提案', 'chat.deliveryBranch': '配信ブランチ', 'chat.changedFiles': '変更ファイル', 'chat.testResults': 'テスト結果' });
Object.assign(en, { 'ops.agentOnline': 'Started' });
Object.assign(zh, { 'ops.agentOnline': '已启动' });
Object.assign(fr, { 'ops.agentOnline': 'Démarré' });
Object.assign(ja, { 'ops.agentOnline': '起動済み' });
Object.assign(en, {
  'resource.confirmProposal': 'Configuration proposal ready',
  'resource.confirmProposalHint': 'Review the Resource Manager response, then explicitly apply this schema-validated proposal. The project will not be started automatically.',
  'resource.applyProposal': 'Apply configuration',
  'restart.team': 'Restart project team',
  'restart.checking': 'Checking restart availability…',
  'restart.running': 'Restarting project team…',
  'restart.confirm': 'Restart the project Admin, Leaders, and Workers? Active tasks block restart. Docker Engine will not be started automatically.',
  'restart.success': 'Project team restarted.',
});
Object.assign(zh, {
  'resource.confirmProposal': '项目团队配置提案已就绪',
  'resource.confirmProposalHint': '请检查资源管理主任的方案后再明确应用。配置会经过 Schema 校验，但不会自动启动项目。',
  'resource.applyProposal': '确认应用配置',
  'restart.team': '重启项目团队',
  'restart.checking': '正在检查是否可以重启…',
  'restart.running': '正在重启项目团队…',
  'restart.confirm': '确定重启项目的 Admin、Leader 和 Worker 吗？存在活动任务时不允许重启，且不会自动启动 Docker Engine。',
  'restart.success': '项目团队已重启。',
});
const dictionaries: Record<Language, Dictionary> = { 'zh-CN': zh, en, fr, ja };

type Theme = 'system' | 'light' | 'dark';
type I18n = { language: Language; setLanguage(language: Language): void; theme: Theme; setTheme(theme: Theme): void; t(key: string): string };
const I18nContext = createContext<I18n | undefined>(undefined);
export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => (localStorage.getItem('oat.language') as Language) || 'zh-CN');
  const [theme, setTheme] = useState<Theme>(() => (localStorage.getItem('oat.theme') as Theme) || 'system');
  useEffect(() => { localStorage.setItem('oat.language', language); document.documentElement.lang = language; }, [language]);
  useEffect(() => { localStorage.setItem('oat.theme', theme); const dark = theme === 'dark' || (theme === 'system' && matchMedia('(prefers-color-scheme: dark)').matches); document.documentElement.dataset.theme = dark ? 'dark' : 'light'; }, [theme]);
  const value = useMemo<I18n>(() => ({ language, setLanguage, theme, setTheme, t: (key) => dictionaries[language][key] ?? en[key] ?? key }), [language, theme]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}
export function useI18n(): I18n { const context = useContext(I18nContext); if (!context) throw new Error('I18nProvider is missing.'); return context; }
